---
title: "Implications of afforestation policies for global markets"
date: "`r format(Sys.time(), '%B %d, %Y')`"
author: "Eric C. Davis, Maros Ivanic, and Brent Sohngen"
output: 
  bookdown::pdf_document2:
    keep_tex: TRUE
toc: FALSE
bibliography: references.bib
header-includes:
    - \usepackage{setspace}\doublespacing
abstract: "The projected growth of the population and incomes as implied by various shared socioeconomic pathways is expected to create  pressures on converting forests into farmland as food prices increase. Depending on the specific path taken, SSP1 through SSP5, and the continuation of the current trends in agricultural productivity growth, the market impacts are expected to vary but generally result in increases in food prices. Policies aimed at reversing the deforestation trend by afforesting cropland would result in severe negative market impacts such as  higher food prices, especially in low agricultural productivity/high population growth scenarios."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

In 2020, there were 4.1 billion hectares of forestland globally covering roughly 31.4% of the land [@fao2023]. These forests play an important role in maintaining and growing the land-based carbon sink by  sequestering about 30% of GHG emissions currently [@roe2019]. This is because of forests proven ability to sequester carbon not only in the stems of trees [@davis2022] but in their soils as well [@guo2021]. With increasingly negative climate impacts, the pressure to enhance the terrestrial sink is growing, and one of the tools to achieve this is afforestation. As such, there is growing attention being placed globally to afforestation efforts, which is highlighted by the UN's declaration of the years from 2021 through 2030 as the UN Decade of Ecosystem Restoration [@sewell2020]. Many of the Nationally Determined Contributions (NDCs) countries have submitted, which detail their plans to keep warming under the 2C threshold, also rely to a significant degree on afforestation projects [@roe2019]. 

The global gains that can be realized from afforestation, however, are uncertain, with broad estimates of cumulative sequestration ranging from 42 gigatonnes to 700 gigatonnes by the end of the century [@veldman2019]  [@bastin2019]  [@humpenoder2014]  [@sathaye2006]  [@doelman2020]. In addition, the amount of land conversion that would be required also varies greatly, with estimates ranging from 0.3 billion hectares to 2.8 billion hectares [@veldman2019]  [@bastin2019]  [@humpenoder2014]  [@doelman2020]. In many cases, these results suggest massive losses in the amount of pasture and cropland that would be available. This puts into question the feasibility of attaining these results, as almost 90 percent of deforestation worldwide is undertaken to expand the amount of agricultural land [@fao2021]. There are many reasons for this. For example, as nations develop and disposable incomes rise, consumers often change to more meat-based diets. Population growth is also a driver and when it is especially high, which is the case at present throughout most of Africa, this also puts pressure on policymakers to allow greater conversion of forestland into farmland. Still, previous research has suggested that substantive gains in the carbon sink (+23.8PgCo2e/yr) can be made without sacrificing agricultural land [@griscom2017]. 

Faced with competing land-use demands, afforestation efforts need to be targeted to the regions of the world where they will provide the most benefits. Afforestation in boreal zones has been shown to provide the smallest net benefits, as the carbon sequestrations benefits of conifer forests are mitigated by the reduction in albedo in winter [@mykleby2017] [@li2015]. Coniferous forests have also been shown to increase soil organic carbon less than broadleaf forests [@guo2021]. Conversely, tropical forests have been linked with a strong positive result from afforestation, as the carbon sequestration benefit is complemented by a cooling impact due to changes in both albedo and evapotranspiration, and with temperate forests, the impact of afforestation is also shown to be positive, albeit less strongly so due to a winter warming effect [@li2015]. 

South America and Sub-Saharan Africa are two regions that show much potential for afforestation. It is estimated that these two regions hold at least 50% of the potential global gain while regions such as Northern Africa and the Middle East show little promise as forest growth rates are quite low [@doelman2020]. Thus, it is promising that the African Forest Landscape Restoration Initiative (AFR100), which aims to afforest 100 million hectares by 2030, has roughly 70% of its commitments coming from Sub-Saharan nations [@auda2023]. While many of these nations may be well-suited in biophysical terms for afforestation, there is concern about how long-lasting any investment may be due to proximate zones of political instability. There are other nations that have a big potential for gains from afforestation, but they also face challenges. India, for example, has a great potential to increase its carbon sequestration through afforestation, but due to its massive population and food security worries, its NDC does not entertain the idea of agricultural land being repurposed and instead primarily considers targeting wastelands that may not be well suited for afforestation [@amjath2019]. Moreover, as land-use decisions in one country also tend to have impacts that spillover into many others [@meyfroidt2010] [@lambin2011], analysis needs to be conducted at a global scale. 

Steinbuks and Hertel [@steinbuks2012] developed the FABLE model (Forestry, Agriculture, Biofuels, Land Use, and Environment) as a global partial equilibrium model to analyze optimal land use within a context of increasing demand for food, bioenergy, forest products, and non-provisioning ecosystem services, while also meeting greenhouse gas targets. The model encompasses nine sectors, including agriculture, livestock, food processing, biofuels, energy, forest, timber processing, and ecosystem services. While FABLE is a powerful tool for examining the optimal trajectory of various land uses under specific demand assumptions, it primarily focuses on specific sectors of the economy, neglecting general equilibrium effects and socio-economic or household welfare impacts [@steinbuks2012] [@hertel2017]. Other efforts have used the Global Trade Analysis Project (GTAP) computable general equilibrium model to address such questions, but its standard model does not well account for land-use changes. As a result, the Land Use and Land Cover Database within the GTAP framework, which incorporates forestry remote-sensing products, was created [@baldos2012]. It was further strengthened as part of the GTAP Agro-Ecological Zone (GTAP-AEZ) model, with the use of spatially explicit global land use data and through the incorporation of intra- and inter-regional land and land-based greenhouse emissions heterogeneity [@hertel2008]. While the GTAP-AEZ model benefits from the inclusion of competition among different crops, grazing, and forest-based uses, it has limitations, primarily due to its infrequent updates. The KLUM@GTAP framework integrated the Kleines Land Use Model (KLUM) with an extended yet static version of GTAP called GTAP-EFL to evaluate the impacts of climate change on cropland allocation. GTAP-EFL separates energy factors from intermediate inputs and incorporates them into capital, while also considering CO2 emissions. KLUM, a global agricultural land-use model, connects the economy to global crop allocation to maximize producer returns under specific risk assumptions. KLUM@GTAP substitutes the land allocation mechanism within GTAP-EFL by utilizing regionally aggregated area changes in cropland determined by KLUM to update cropland shares in GTAP-EFL [@ronneberger2009].

More recent modeling attempts of land-use change have begun to move away from comparative static analysis. For example, the dynamic GTAP model, supported by the GTAP-AEZ database, considers land market effects, which were identified as significant in driving results by Stevenson et al. [@stevenson2013], and has been utilized to evaluate the impacts of crop intensification on land use. It, however, has been critiqued, as global aggregates may mask localized shifts that can have implications for ecologically significant areas [@byerlee2014]. In addition, in the standard GTAP model, it is difficult to model a sector individually. There are 68 market sectors covered in the latest version of the GTAP database. The GTAP model's general equilibrium nature means that all these markets are cleared with market-clearing prices. As the model applies nested CES production functions to all sectors and differentiates them by parameters only, to model one sector, in this case forestry, differently from the rest would require a major redesign of the model. While not impossible, this project will attempt to get around these concerns and assess the impact of various likely land-use scenarios by melding GTAP with the Global Timber Model (GTM), which is a dynamic optimization model that has been specifically designed to analyze the relationship among land rents, forested land cover, and carbon sequestration through forests and thus is better able to examine the impact of afforestation or avoided deforestation on the carbon sink [@sohngen2001]. The latest versions of both models were used. For the GTAP model, this meant using the 11b data which has 2017 as a base year. This data was then updated to the base year (2023) using data from the Centre for Prospective Studies and International Information (CEPII) to account for the projected changes in gross domestic product (GDP), population, and productivity for each country in the world. 


# Connecting the GTAP and GTM models

By joining these two models and passing outputs back and forth between the models, any limitations of either model should be minimized and more robust results, therefore, should be attained. Establishing a connection between the standard GTAP model and the GTM model required  a two-step process. First, we identified the set of common variables that are included in both models and their closures. That is, we selected which variables would be determined endogenously by one model and held as exogenous in the other model. In our case, we modeled the return on land using the GTAP model and fed those results into the GTM model as exogenous. Then, the amount of land available for crop and livestock production was endogenously determined by the GTM model and fed into the GTAP model as an exogenous input. In the second step, we established the connection between the models on the software level. This step required that the GTAP model, which is written in GEMPACK, be able to handle with the inputs from the GTM model, which is written in GAMS, and submit the outputs back to the GTM model. As GEMPACK and GAMS were developed long before software integration became important or even possible, we had to create a set of user functions in R that executed both models, collected their outputs, and created parameter files automatically.

Once R was able to operate both models automatically, we were then able to formulate the combined solution as a fairly simple math program that is solved in R:

\begin{equation}
\mbox{GTAP}:V_1\to V_2
\end{equation}

\begin{equation}
\mbox{GTM}:V_2\to V_1
\end{equation}

\begin{equation}
s.t. V_2 = V_1
\end{equation}

where $V_1$ is a vector of all the variables in both systems, i.e., all variables in GTAP and all variables in GTM. Of import, $V_1$ includes the land change variables, which are exogenous to the GTAP model. $V_1$ is then used by the GTAP model (represented by function \mbox{GTAP}) and its outputs are passed to GTM as a vector of variables $V_2$. This output vector contains the change in rents, which is treated as exogenous in the GTM model. GTM then processes the $V_2$ variables as inputs and passes its solution back to GTAP as $V_1$. To solve the system simultaneously, we require that $V_1$ and $V_2$ be equal. With several iterations, the system converges to the change in land and land rent that is consistent across the models, i.e., the land change results in the land rent changes that, when entered into the GTM model, result in the same land changes as assumed by the GTAP model.


# Modeling the impact of possible measures to mitigate deforestation/promote afforestation 

To understand the impact of potential regional and global afforestation actions, an important first step was creating a realistic baseline scenario that depicts the likely changes between over the decade under study: 2023-2033. This was done by taking into account key drivers of change like growth in population and GDP. Without accounting for this, results would likely have been biased as they would have failed to account for the increasing pressure to convert forests into agricultural land. Data for this were drawn from sources such as CEPII and the United Nations. 

When examining the likely impacts of the baseline changes alone, it is estimated that by 2033, significant deforestation would have occured in many regions of the world. For example, in Brazil... 

Then, we examined what it would take given the pressures of a still growing global population with the concomitant increasing appetite for foodstuffs to end, on net, the practice of deforestation globally. Results suggest that it would require a tax of roughly 70.3 percent to be assessed on the value of the converted land for the deforestation rate to fall globally to roughly zero. The economic impact of such a policy measure would not be limited to the cost of the tax, it would also change impact food production and global trade. For example, with this policy in place, most regions of the world would see significant declines in the amount of agricultural land in 2033 relative to the baseline scenario where land conversion was not taxed. For the United States, agricultural land would be 2.1 percent less (Table 1). Larger decreases would happen in other major agricultural production regions such as China (-2.5 percent), South Asia (-8.0 percent), Brazil (-8.5 percent), and Russia (-9.3 percent). 

Table 1 qo-Land
				∆ (%)
East Asia			-14.6
Central America			-14.5
North Africa & the Middle East	-10.3
Russia				-9.3
Southeast Asia			-9.0
Brazil				-8.5
Rest of South America		-11.7
South Asia			-8.0
Canada				-7.9
West & Central Europe 		-6.2
Oceania				-5.9
Sub-Saharan Africa		-4.1
China				-2.5
United States			-2.2
Japan				17.5



These reductions in the amount of agricultural land prompt changes in the quantity of agricultural goods produced for many regions. For example, East Asia and Southeast Asia see the largest declines in percentage terms in agricultural production with decreases of 5.1 percent and 2.0 percent, respectively (Table 2). Surprisingly, Brazil and the United States, despite the derease in available agricultural land compared to the baseline 2033 scenario, see increased agricultural output of 0.2 percent and 0.6 percent, respectively. This may be tied to the sharp declines in other regions prompting greater production for export. 

Table 2 qo-Ag
				∆ (%)
				Agriculture
East Asia			-5.1
Southeast Asia			-2.0
Central America			-2.0
South Asia			-1.1
North Africa & the Middle East	-0.9
Sub-Saharan Africa		-0.3
China				-0.1
Russia				0.1
Brazil				0.2
Rest of South America		-1.2
West & Central Europe 		0.4
United States			0.6
Oceania				0.7
Canada				1.3
Japan				1.4


When we examine how this impacts exports of agricultural goods, we find that Japan and the United States appear to be the biggest beneficiaries of this policy with their exports increasing 8.8 percent and 3.5 percent, respectively (table 3). The regions where agricultural exports drop most significantly are East Asia, South Asia, Southeast Asia, and Central America who see decreases of 14.5 percent, 5.9 percent, 5.1 percent,and 5.0 percent, respectively. 

Table 3 qxw-Ag
				∆ (%)
				Agriculture
Japan				8.78
United States			3.49
Canada				3.13
China				1.96
Oceania				1.67
Russia				1.52
West & Central Europe 		1.16
Brazil				1.03
Rest of South America		-2.67
Sub-Saharan Africa		0.02
North Africa & the Middle East	-1.52
Central America		-5.02
Southeast Asia		-5.14
South Asia		-5.94
East Asia		-14.45

Overall, this policy, while avoiding deforestation, has a rather significant negative economic impact on all regions except Japan and Canada who see an increase in consumer well-being of $977.1 million and $166.9 million, respectively (table 4). Consumer well-being is a measurement of equivalent variation and here measures the benefit/harm consumers experience in terms of income as a result of the policy changes. The United States, along with 10 other regions, see well-being drop by more than $1 billion. The most negatively impacted regions are South Asia (-28.0 billion), China (-14.5 billion), and Southeast Asia (-13.6 billion). In total, such a policy is estimated to decrease global consumer well-being by $92.1 billion. 


Table 4 EV
				∆ ($)
Japan				977,125,000
Canada				166,937,500
Oceania				-169,625,000
EUII				-588,500,000
Brazil				-735,125,000
United States			-1,085,000,000
Russia				-1,152,375,000
Rest of South America		-3,848,625,000
Central America			-4,471,500,000
North Africa & the Middle East	-5,012,125,000
East Asia			-5,065,625,000
West & Central Europe		-7,152,500,000
Sub-Saharan Africa		-7,850,500,000
Southeast Asia			-13,601,000,000
China				-14,452,000,000
South Asia			-28,024,000,000


Much of this loss in well-being may be the result of higher prices. Japan is the only nation that sees any positive price impacts resulting from this policy, with the price of agricultural goods decreasing 0.3 percent (table 5). All other regions, for both agricultural and non-agricultural products, see prices rise between 0.3 and 5.1 percent. 

Table 5 pm
									∆ (%)				
	Agricultural Goods		Forest Products		Lumber		Paper Products		Other Non-Agricultural Goods
Oceania						1.2	0.4	0.5	0.5	0.5
China						1.1	0.4	0.4	0.4	0.4
Japan						-0.3	0.4	0.4	0.4	0.4
East Asia					5.1	0.3	0.3	0.3	0.4
Southeast Asia					2.8	0.3	0.3	0.4	0.3
South Asia					3.1	0.3	0.3	0.3	0.3
Canada						0.7	0.5	0.5	0.5	0.5
United States					0.7	0.5	0.5	0.5	0.5
Central America					2.5	0.3	0.3	0.4	0.3
Brazil						1.2	0.5	0.5	0.5	0.5
Rest of South America				2.1	0.3	0.3	0.3	0.3
West & Central Europe 				0.9	0.4	0.4	0.4	0.4
Russia						1.1	0.4	0.4	0.4	0.4
Sub-Saharan Africa				1.5	0.4	0.4	0.4	0.4
North Africa & the Middle East			2.0	0.4	0.4	0.4	0.4

Land price seems weird. I have it decreasing????




1a) On aggregate zero percent net deforestation Globally

1) Full attainment of AFR100 pledges as part of Bonn Challenge: This says that there will be a 127.81 million hectare increase in forest area just in Sub-Saharan Africa by 2030 [@bonn2023]. To see the list of countries and the hectares pledged, please view Scenario 1 of the Excel document "Bonn Challenge-Africa".

2) Partial attainment of AFR100 pledges as part of Bonn Challenge: This scenario analyzes full attainment for nations with conflict severity level less than or equal to limited and 0% attainment for regions with a higher conflict severity rating. Using this measure, there would only be a 54.95 million hectare increase in forest area by 2030 [@bonn2023]  [@acled2023]. To see the list of countries and the hectares pledged, please view Scenario 2 of the Excel document "Bonn Challenge-Africa".

3) Full attainment of Latin America pledges as part of Bonn Challenge: This says that there will be a 33.64 million hectare increase in forest area by 2030 [@bonn2023]. To see the list of countries and the hectares pledged, please view the Latin America tab of the Excel document "Bonn Challenge-Other Regions".

4) Full attainment of tropical nations' pledges as part of Bonn Challenge: This says that there will be a 182.30 million hectare increase in forest area by 2030 [@bonn2023]. To see the list of countries and the hectares pledged, please view the Tropical Forest tab of the Excel document "Bonn Challenge-Other Regions". Nations that lie in both tropical and sub-tropical zones and taken to be tropical.

5) Full attainment of UN strategic plan for forests 2030 (UNFF): This says that all deforestation will halt and there will be a 3% (~120 million hectare) increase in forest area worldwide by 2030 [@sewell2020]. This will be modeled as a uniform 3% increase in forested area across all nations.

6) Expansion of UN strategic plan for forests: This says that all deforestation will halt and there will be a 15% (~600 million hectare) increase in forest area worldwide by 2030 [@sewell2020]. This will be modeled as a uniform 15% increase in forested area across all nations.



[@defries2010] found a strong correlation between forest loss and exports of agricultural products. On the other hand, [@turner2005] investigated the role of trade on forests in the context of the Free Trade Area of the Americas (FTAA) using the spatial partial-equilibrium Global Forest Products Model and found that FTAA has a positive impact on forest resources.
# References
