$onMultiR;
$ontext;

$offtext;

TABLE PARAM2_N2(CTRY,LC1,DATA)
$ondelim
$include param2n_042120.csv
$offdelim
;


TABLE PARAM3_N2(CTRY,LC1,DATA)
$ondelim
$include param3_042420.csv
$offdelim
;

*harvesting cost parameters
TABLE PARAM4_N2(CTRY,LC1,DATA)
$ondelim
$include param4_042220.csv
$offdelim
;

TABLE CPARAM2_N2(CTRY,LC1,DATA)
$ondelim
$include cparam_p6_042220.csv
$offdelim
;

*Accessible forest initial inventory
TABLE FORINV2_N2(CTRY,LC1,A1)
$ondelim
$include forinv2_p6_2020.csv
$offdelim
;

*inaceessible forest initial inventory
TABLE IFORIN2_N2(CTRY,LC1,A1)
$ondelim
$include iforiN2_p6_2020.csv
$offdelim
;

PARAM2(CTRY,LC1,DATA)=PARAM2_N2(CTRY,LC1,DATA);
PARAM3(CTRY,LC1,DATA)=PARAM3_N2(CTRY,LC1,DATA);
PARAM4(CTRY,LC1,DATA)=PARAM4_N2(CTRY,LC1,DATA);
CPARAM2(CTRY,LC1,DATA)=CPARAM2_N2(CTRY,LC1,DATA);
FORINV2(CTRY,LC1,A1)= FORINV2_N2(CTRY,LC1,A1);
IFORIN2(CTRY,LC1,A1)= IFORIN2_N2(CTRY,LC1,A1);

INACI2(CTRY,LC1,A1) = IFORIN2(CTRY,LC1,A1);

*define for later use
CSA(CTRY,LC1,DATA) = PARAM4(CTRY,LC1,DATA);



* Reset demand parameters 
* US ONLY: USADJUST /0.15/;
* Adjust for full market model = 0.5

USADJUST =0.75;

PARAMETER AF(T);
AF(T) = USADJUST*POPGR2(T)*2300*FORTCHG(T)*(GDPPC(T)**FINCELAS(T));

PARAMETER AFP(T);
AFP(T) = AF(T)*.20;

PARAMETER AFS(T);
AFS(T) = AF(T) - AFP(T);


*****************************************************************
*adjust forlimit for Central America 
FORLIMIT('9')=115;

$ONTEXT;
Original forlimit

PARAMETER FORLIMIT(CTRY)			
/	1	495.5	,
	2	573.2	,
	3	634.5	,
	4	603.3	,
	5	1056.1	,
	6	432.4	,
	7	170.2	,
	8	89	,
	9	94.4	,
	10	440.6	,
	11	593.2	,
	12	438	,
	13	210	,
	14	33	,
	15	70.4	,
	16	22.9	/;

$offtext;

$ONTEXT;
This section calculates shifts in the rental functions to account for exogenous changes in demand for alternative uses of land
$OFFTEXT;

PARAMETER RNTSHFT(CTRY,LC1,T);
RNTSHFT(CTRY,LC1,'1') = 1;
LOOP[T, RNTSHFT(CTRY,LC1,T+1)=
        {RNTSHFT(CTRY,LC1,T)*(1+PARAM3(CTRY,LC1,'2')*
                ((1-PARAM3(CTRY,LC1,'3'))**{ORD(T)-1}))}$(PARAM3(CTRY,LC1,'2') NE 0)+

        RNTSHFT(CTRY,LC1,T)$(PARAM3(CTRY,LC1,'2') EQ 0)];

DISPLAY RNTSHFT;

PARAMETER RENTA(CTRY,LC1,T);
RENTA(CTRY,LC1,T) =
        PARAM2(CTRY,LC1,'16')*RNTSHFT(CTRY,LC1,T)$(R1FOR(CTRY,LC1) EQ 1)+

        PARAM2(CTRY,LC1,'16')*RNTSHFT(CTRY,LC1,T)$(DEDBIO(CTRY,LC1) EQ 1)+

        PARAM2(CTRY,LC1,'16')*RNTSHFT(CTRY,LC1,T)$(TROPINAC(CTRY,LC1) EQ 1);

PARAMETER RENTB(CTRY,LC1);
RENTB(CTRY,LC1)=PARAM2(CTRY,LC1,'17');

PARAMETER RENTAF(CTRY,LC1);
RENTAF(CTRY,LC1) = SUM[T$(FINT(T)),RENTA(CTRY,LC1,T)$(FINT(T))];

PARAMETER RENTZ(CTRY,LC1,T);
RENTZ(CTRY,LC1,T) = PARAM2(CTRY,LC1,'18')*(1/RNTSHFT(CTRY,LC1,T));

PARAMETER RENTHA(CTRY,LC1,T);
RENTHA(CTRY,LC1,T) =
{[RENTZ(CTRY,LC1,T)/RENTA(CTRY,LC1,T)]**RENTB(CTRY,LC1)}$(TROPINAC(CTRY,LC1) EQ 1);

DISPLAY RENTA,RENTZ,RENTHA;


$ONTEXT;
FINPTEL adjusts parameter that affects the elasticity of management inputs in forestry to account for technology change.  Currently assume 0.3% per decade growth in elasticity
$OFFTEXT;

PARAMETER FINPTEL(CTRY,LC1,T);
FINPTEL(CTRY,LC1,'1')$(R1FOR(CTRY,LC1) EQ 1)=
        PARAM2(CTRY,LC1,'9');
LOOP[T,FINPTEL(CTRY,LC1,T+1)$(R1FOR(CTRY,LC1) EQ 1)=
                FINPTEL(CTRY,LC1,T)*(1.003)];

FINPTEL(CTRY,LC1,'1')$(DEDBIO(CTRY,LC1) EQ 1)=
        PARAM2(CTRY,LC1,'9');
LOOP[T,FINPTEL(CTRY,LC1,T+1)$(DEDBIO(CTRY,LC1) EQ 1)=
                FINPTEL(CTRY,LC1,T)*(1.003)];

DISPLAY FINPTEL;

PARAMETER FINPTELF(CTRY,LC1);
FINPTELF(CTRY,LC1) = SUM[T$(FINT(T)),FINPTEL(CTRY,LC1,T)$(FINT(T))];

DISPLAY FINPTELF;


*Generate forest yield functions
* GINIT = decadal forest growth
* note that these include adjustments to forest growth to account for climate change through CHG1, but 
* those parameters are set to 0 in the baseline.
PARAMETER GINIT1(CTRY,LC1,A1,T);
GINIT1(CTRY,LC1,A1,T)$(ALLIN(CTRY,LC1) EQ 1) = 0$(ORD(A1) LT PARAM2(CTRY,LC1,'3')) +
                0$(ORD(A1) EQ PARAM2(CTRY,LC1,'3')) +

                SUM(TT,(1+CHG1(CTRY,LC1,T,'1'))*

                ((PARAM2(CTRY,LC1,'2')/(((ORD(A1)-PARAM2(CTRY,LC1,'3')-1)*10+ORD(TT)-.5)**2))*
                EXP(PARAM2(CTRY,LC1,'1')-PARAM2(CTRY,LC1,'2')/((ORD(A1) -
                                PARAM2(CTRY,LC1,'3')-1)*10 +
                ORD(TT)-.5))))$(ORD(A1) GT PARAM2(CTRY,LC1,'3'));

*Also decadal growth
PARAMETER GROWTH1(CTRY,LC1,A1,T);
GROWTH1(CTRY,LC1,A1,T)$(ALLIN(CTRY,LC1) EQ 1) = 0$(ORD(A1) LT PARAM2(CTRY,LC1,'3')) +
                0$(ORD(A1) EQ PARAM2(CTRY,LC1,'3')) +

                SUM(TT,(1+CHG1(CTRY,LC1,T,'1'))*
                ((PARAM2(CTRY,LC1,'2')/(((ORD(A1)-PARAM2(CTRY,LC1,'3')-1)*10+
                                ORD(TT)-.5)**2))*
                EXP(PARAM2(CTRY,LC1,'1')-PARAM2(CTRY,LC1,'2')/((ORD(A1) -
                                PARAM2(CTRY,LC1,'3')-1)*10 +
                ORD(TT)-.5))))$(ORD(A1) GT PARAM2(CTRY,LC1,'3'));

*initial age class growth in each time period
PARAMETER YINIT1(CTRY,LC1,A1,T);
YINIT1(CTRY,LC1,'1',T) = GINIT1(CTRY,LC1,'1',T);
LOOP(A1,YINIT1(CTRY,LC1,A1+1,T) = YINIT1(CTRY,LC1,A1,T) + GINIT1(CTRY,LC1,A1+1,T));

DISPLAY GINIT1,YINIT1;

*YIELD2 is growth function, summed over decadal growth
PARAMETER YIELD2(CTRY,LC1,A1,T) yield function;

YIELD2(CTRY,LC1,A1,T) = YINIT1(CTRY,LC1,A1,T)$TFIRST(T);
YIELD2(CTRY,LC1,A1,T)$AFIRST1(A1) = GROWTH1(CTRY,LC1,A1,T)$AFIRST1(A1);
LOOP(T,LOOP(A1,YIELD2(CTRY,LC1,A1+1,T+1)=YIELD2(CTRY,LC1,A1,T)+
        GROWTH1(CTRY,LC1,A1+1,T+1)));

*create YIELDORIG(CTRY,LC1,A1,T) which is used later for carbon calculations
* Use YIELD2 divided by quality adjustment parameter
PARAMETER YIELDORIG(CTRY,LC1,A1,T);
YIELDORIG(CTRY,LC1,A1,T) = YIELD2(CTRY,LC1,A1,T);

*Quality adjustment � accounts for value differences across logs from different regions.
YIELD2(CTRY,LC1,A1,T) = YIELD2(CTRY,LC1,A1,T)*PARAM3(CTRY,LC1,'4');


DISPLAY YIELD2;

*Add in underlying productivity changes in yields for productive species
*original method of shifting yields
*these are 6% per decade for many plantation types, and 3% per decade for others following
* estimates in Scholze et al. (2006)
PARAMETER YDGRTH(CTRY,LC1,T);
YDGRTH(CTRY,LC1,'1') = 1;

LOOP(T,YDGRTH(CTRY,LC1,T+1) = YDGRTH(CTRY,LC1,T) +
((PARAM3(CTRY,LC1,'9'))*YDGRTH(CTRY,LC1,T)*
       (.99**[(ORD(T)-1)*10]))$(PARAM3(CTRY,LC1,'1') EQ 1)+
(PARAM3(CTRY,LC1,'9'))*YDGRTH(CTRY,LC1,T)$(PARAM3(CTRY,LC1,'1') EQ 0)
);

PARAMETER YDGRTH2(CTRY,LC1,T);
YDGRTH2(CTRY,LC1,'1') = 1;

LOOP(T,YDGRTH2(CTRY,LC1,T+1) = YDGRTH2(CTRY,LC1,T) +
((PARAM3(CTRY,LC1,'9'))*YDGRTH2(CTRY,LC1,T)*(.99**[(ORD(T)-1)*10])));


YIELD2(CTRY,LC1,A1,T)= YIELD2(CTRY,LC1,A1,T)*YDGRTH(CTRY,LC1,T);
YIELDORIG(CTRY,LC1,A1,T) = YIELDORIG(CTRY,LC1,A1,T)*YDGRTH(CTRY,LC1,T);

DISPLAY YDGRTH, YIELD2;


*Technology change adjustment for merchantable timber out of biomass stock
*Not included in this version; assumed to be 0
PARAMETER TSWCHG(CTRY,LC1);
TSWCHG(CTRY,LC1) = 0;

PARAMETER MXSWTM(CTRY,LC1,T);
MXSWTM(CTRY,LC1,'1')$(ALLIN(CTRY,LC1) EQ 1)=
        PARAM2(CTRY,LC1,'4')$(ALLIN(CTRY,LC1) EQ 1);
LOOP[T,MXSWTM(CTRY,LC1,T+1) $(ALLIN(CTRY,LC1) EQ 1) =
        MXSWTM(CTRY,LC1,T)*(1+ TSWCHG(CTRY,LC1))];


$ONTEXT;
 The following routines adjust the yield function to account for the merchantable proportion of stock
 on each hectare.
The final result below takes the original yield function from above and multiplies by a factor that adjusts the biomass on site for the proportion that is merchantable, depending on the age class.

YIELD2 = YIELD2*SWPERC2A

$OFFTEXT;

PARAMETER SWGRTH(CTRY,LC1);
SWGRTH(CTRY,LC1) =2.0$(PARAM2(CTRY,LC1,'11') EQ 1)+
1.0$( PARAM2(CTRY,LC1,'11') EQ 2)+
0.9$( PARAM2(CTRY,LC1,'11') EQ 3)+
0.6$( PARAM2(CTRY,LC1,'11') EQ 4)+
0.5$( PARAM2(CTRY,LC1,'11') GT 4);


PARAMETER SWPERC2A(CTRY,LC1,A1,T);
SWPERC2A(CTRY,LC1,A1,T)$(ALLIN(CTRY,LC1) EQ 1)=

{MXSWTM(CTRY,LC1,T)*[1-EXP((-0.4/(PARAM2(CTRY,LC1,'11')*10-ORD(A1)*10+10))*
(ORD(A1)*10))]**2}$(ORD(A1) LT PARAM2(CTRY,LC1,'11'))+

{MXSWTM(CTRY,LC1,T)*[1-EXP((-SWGRTH(CTRY,LC1)/10)*
(ORD(A1)*10))]**2}$(ORD(A1) EQ PARAM2(CTRY,LC1,'11'))+

{MXSWTM(CTRY,LC1,T)*[1-EXP((-SWGRTH(CTRY,LC1)/10)*
(ORD(A1)*10))]**2}$(ORD(A1) GT PARAM2(CTRY,LC1,'11'));

*AGETR age to start counting sawtimber quantity
PARAMETER AGETR(CTRY,LC1);
AGETR(CTRY,LC1) = PARAM2(CTRY,LC1,'6');

*SWPC2A shifts SWPERC2A up by the number of decades in AGETR.
PARAMETER SWPC2A(CTRY,LC1,A1,T);
LOOP[A1,SWPC2A(CTRY,LC1,A1,T) = 0$(ORD(A1) LT AGETR(CTRY,LC1)) +
       0$(ORD(A1) EQ AGETR(CTRY,LC1))+
       SWPERC2A(CTRY,LC1,A1-AGETR(CTRY,LC1),T)$(ORD(A1) GT AGETR(CTRY,LC1))];

DISPLAY SWPC2A;

SWPERC2A(CTRY,LC1,A1,T)$(ALLIN(CTRY,LC1) EQ 1)=SWPC2A(CTRY,LC1,A1,T);

SWPERC2A(CTRY,LC1,A1,T)$(ALLIN(CTRY,LC1) EQ 1) = MIN[SWPERC2A(CTRY,LC1,A1,T),10];

YIELD2(CTRY,LC1,A1,T)$(ALLIN(CTRY,LC1) EQ 1)=YIELD2(CTRY,LC1,A1,T)*SWPERC2A(CTRY,LC1,A1,T);

DISPLAY SWPERC2A, YIELD2;

PARAMETER YIELD2F(CTRY,LC1,A1);
YIELD2F(CTRY,LC1,A1)=SUM[T$(FINT(T)),YIELD2(CTRY,LC1,A1,T)$(FINT(T))];

*create inaccessible yield functions � already adjusted for merch proportion
PARAMETER YLDINAC(CTRY,LC1,A1,T);
YLDINAC(CTRY,LC1,A1,T) = YIELD2(CTRY,LC1,A1,T);

execute_unload "GTM_2020_R2.gdx"

*Estimate terminal values
*a discount factor
PARAMETER DELTA1(CTRY,LC1);
DELTA1(CTRY,LC1) = 1/[(1-EXP(-R*PARAM2(CTRY,LC1,'11')*10))$(ALLIN(CTRY,LC1) EQ 1) +
                                1$(ALLIN(CTRY,LC1) EQ 0)];

*Estimate terminal management values
PARAMETER MNG1(CTRY,LC1);
MNG1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) =
SUM(A1,{[{[(1/(1+R))**(-PARAM2(CTRY,LC1,'11')*10)]*

(1/((PTERM - PARAM2(CTRY,LC1,'10')$(ALLIN(CTRY,LC1) EQ 1))*
PARAM2(CTRY,LC1,'8')$(ALLIN(CTRY,LC1) EQ 1)*FINPTELF(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1)*
        YIELD2F(CTRY,LC1,A1)$(ALLIN(CTRY,LC1) EQ 1)+EPSILON))}**(1/( FINPTELF(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1)-1))]
-1}$(ORD(A1) EQ PARAM2(CTRY,LC1,'11')));

MNG1(CTRY,LC1) = MAX[MNG1(CTRY,LC1),0];

PARAMETER MNG1A(CTRY,LC1);
MNG1A(CTRY,LC1)=MIN[MNG1(CTRY,LC1),MANT];

DISPLAY MNG1, MNG1A;


*alternate calculation of MNG1/A
PARAMETER ZIM1(CTRY,LC1);
ZIM1(CTRY,LC1)=0;
LOOP(CTRY,
LOOP[LC1$(ALLIN(CTRY,LC1) EQ 1),
WHILE(

SUM{A1,[(1+R)**(-10*ORD(A1))]*(PTERM - PARAM2(CTRY,LC1,'10'))*
        (PARAM2(CTRY,LC1,'8')*FINPTELF(CTRY,LC1)*
        (ZIM1(CTRY,LC1)+1+EPSILON)**(FINPTELF(CTRY,LC1)-1))*
        YIELD2F(CTRY,LC1,A1)$(ORD(A1) EQ PARAM2(CTRY,LC1,'11'))}


GT 1,

ZIM1(CTRY,LC1)= ZIM1(CTRY,LC1)+1);
]
)
;

PARAMETER MNG1A(CTRY,LC1);
MNG1A(CTRY,LC1)=MIN[ZIM1(CTRY,LC1),MANT];
MNG1(CTRY,LC1) = MNG1A(CTRY,LC1);

*determine rotation age and net present values

PARAMETER NC1(CTRY,LC1,A1);
NC1(CTRY,LC1,A1)=0;
PARAMETER NPVCS1(CTRY,LC1,AC1);
NPVCS1(CTRY,LC1,AC1)=0;

PARAMETER NPVSS1(CTRY,LC1,A1);
NPVSS1(CTRY,LC1,A1) =
{(PTERM - PARAM2(CTRY,LC1,'10'))*
        {(PARAM2(CTRY,LC1,'8')*(MNG1A(CTRY,LC1)+1+EPSILON)** FINPTELF(CTRY,LC1))*
        YIELD2F(CTRY,LC1,A1)*((1+R)**(-ORD(A1)*10))}+
        SUM(AC1,NPVCS1(CTRY,LC1,AC1)$(ORD(AC1) EQ ORD(A1)))
        - MNG1A(CTRY,LC1)}/{1-((1+R)**(-ORD(A1)*10))};

DISPLAY NPVSS1;

PARAMETER NPVT1;

PARAMETER NPVT2

PARAMETER TMAGE1(CTRY,LC1);
TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) = 1;

LOOP(CTRY,
LOOP(LC1$(ALLIN(CTRY,LC1) EQ 1),
LOOP(A1, NPVT1=NPVSS1(CTRY,LC1,A1);
        NPVT2 = NPVSS1(CTRY,LC1,A1+1);


IF (NPVT1<NPVT2, TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) =TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1)+1;
        ELSEIF (NPVT1=NPVT2), TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) =TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1)+1;
        ELSE TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) = TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1));
        );
IF (NPVT1 <0, TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) = TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1)-1;
        ELSE TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) = TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) ;
        );
        );
      );

DISPLAY TMAGE1;
PARAM2(CTRY,LC1,'11')$(ALLIN(CTRY,LC1) EQ 1)=TMAGE1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1);


*Determine SS area of accessible forests
*calculate decadal rental value
PARAMETER PVADDA1(CTRY,LC1);
PVADDA1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) =
        SUM[A1,NPVSS1(CTRY,LC1,A1)$(ORD(A1) EQ PARAM2(CTRY,LC1,'11'))]-
        SUM[A1,NPVSS1(CTRY,LC1,A1)$(ORD(A1) EQ PARAM2(CTRY,LC1,'11'))]/(1+R);

PARAMETER TFINAC1(CTRY,LC1);
TFINAC1(CTRY,LC1)$(R1FOR(CTRY,LC1) EQ 1) =
        [PVADDA1(CTRY,LC1)/RENTAF(CTRY,LC1)]**RENTB(CTRY,LC1);

TFINAC1(CTRY,LC1)$(TROPINAC(CTRY,LC1) EQ 1) =
        [PVADDA1(CTRY,LC1)/RENTAF(CTRY,LC1)]**RENTB(CTRY,LC1);

DISPLAY PVADDA1,TFINAC1;

TFINAC1(CTRY,LC1)$(ALLIN(CTRY,LC1) EQ 1) = TFINAC1(CTRY,LC1)/PARAM2(CTRY,LC1,'11');

PARAMETER FINAC1(CTRY,LC1,A1);
FINAC1(CTRY,LC1,A1)$(ALLIN(CTRY,LC1) EQ 1) =
        TFINAC1(CTRY,LC1)$(ORD(A1) LT (PARAM2(CTRY,LC1,'11')+1));

LOOP(CTRY,
LOOP(LC1$(ALLIN(CTRY,LC1) EQ 1),
       IF((PARAM2(CTRY,LC1,'11')) = 15,
       LOOP[A1, FINAC1(CTRY,LC1,A1) = 0$(ORD(A1) LT (PARAM2(CTRY,LC1,'11')))+
       TFINAC1(CTRY,LC1)*PARAM2(CTRY,LC1,'11')$(ORD(A1) EQ (PARAM2(CTRY,LC1,'11')))];
        ELSE LOOP(A1,
       IF (ORD(A1)< (PARAM2(CTRY,LC1,'11')+1),
                FINAC1(CTRY,LC1,A1) = TFINAC1(CTRY,LC1);
                ELSE FINAC1(CTRY,LC1,A1) =0;
       ););
        );
);
);

TFINAC1(CTRY,LC1)=TFINAC1(CTRY,LC1)*PARAM2(CTRY,LC1,'11');

DISPLAY TFINAC1,FINAC1;

*Estimate Terminal Conditions
PARAMETER ALPHAK1(CTRY,LC1,A1);

ALPHAK1(CTRY,LC1,A1) = (PTERM - PARAM2(CTRY,LC1,'10'))*
        (PARAM2(CTRY,LC1,'8')*(MNG1(CTRY,LC1)+1+EPSILON)**FINPTELF(CTRY,LC1))*
        YIELD2F(CTRY,LC1,A1)-MNG1A(CTRY,LC1);

PARAMETER ALPHA1(CTRY,LC1);
ALPHA1(CTRY,LC1)=SUM(A1,ALPHAK1(CTRY,LC1,A1)$(ORD(A1) EQ PARAM2(CTRY,LC1,'11')));

DISPLAY ALPHAK1,ALPHA1;

PARAMETER ALPHAK1(CTRY,LC1,A1);
ALPHAK1(CTRY,LC1,A1) = (PTERM - PARAM2(CTRY,LC1,'10'))*
        (PARAM2(CTRY,LC1,'8')*(MNG1(CTRY,LC1)+1+EPSILON)**FINPTELF(CTRY,LC1))*
        YIELD2F(CTRY,LC1,A1)-MNG1A(CTRY,LC1);


PARAMETER BETA1(CTRY,LC1);
BETA1(CTRY,LC1) = SUM(A1, [(PTERM - PARAM2(CTRY,LC1,'10'))*
        (PARAM2(CTRY,LC1,'8')*FINPTELF(CTRY,LC1)*
       (MNG1(CTRY,LC1)+1+EPSILON)**(FINPTELF(CTRY,LC1)-1))*
        YIELD2F(CTRY,LC1,A1)]$(ORD(A1) EQ PARAM2(CTRY,LC1,'11')));
DISPLAY BETA1;

BETA1(CTRY,LC1) =0;
LOOP{A1,

BETA1(CTRY,LC1) = BETA1(CTRY,LC1)+
        [(PTERM - PARAM2(CTRY,LC1,'10'))*
        (PARAM2(CTRY,LC1,'8')*FINPTELF(CTRY,LC1)*
       (MNG1(CTRY,LC1)+1+EPSILON)**(FINPTELF(CTRY,LC1)-1))*
        YIELD2F(CTRY,LC1,A1)]$(ORD(A1) EQ PARAM2(CTRY,LC1,'11'))
};


DISPLAY MNG1,BETA1;

*LAMBDA1 is actual terminal condition in $/ha for each age class
PARAMETER LAMBDA1(CTRY,LC1,A1);
LAMBDA1(CTRY,LC1,A1)$(ALLIN(CTRY,LC1) EQ 1) = {[(1/(1+R))**([PARAM2(CTRY,LC1,'11') - ORD(A1)]*10)]*
        DELTA1(CTRY,LC1)*ALPHA1(CTRY,LC1)}$(ORD(A1) LT (PARAM2(CTRY,LC1,'11')+1)) +
       {(DELTA1(CTRY,LC1)-1)*ALPHA1(CTRY,LC1) + ALPHAK1(CTRY,LC1,A1)}$(ORD(A1) GT PARAM2(CTRY,LC1,'11'));

LAMBDA1(CTRY,LC1,A1)$(ALLIN(CTRY,LC1) EQ 1)=
LAMBDA1(CTRY,LC1,A1)$(ORD(A1) LT PARAM2(CTRY,LC1,'11')+1)+
0$(ORD(A1) GT PARAM2(CTRY,LC1,'11'));

*PSI1 is actual terminal condition for $ spent on management
PARAMETER PSI1(CTRY,LC1,A1);
PSI1(CTRY,LC1,A1)$(ALLIN(CTRY,LC1) EQ 1) =
        {[(1/(1+R))**([PARAM2(CTRY,LC1,'11')-ORD(A1)]*10)]*BETA1(CTRY,LC1)}$(ORD(A1)
       LT (PARAM2(CTRY,LC1,'11')+1)) + 0$(ORD(A1) GT PARAM2(CTRY,LC1,'11'));


DISPLAY LAMBDA1,PSI1;

*adjust initial forest management
PARAMETER MTFIN1(CTRY,LC1,A1);
MTFIN1(CTRY,LC1,A1) = MNG1(CTRY,LC1);

PARAMETER MTINIT(CTRY,LC1,A1);
MTINIT(CTRY,LC1,A1) = MTFIN1(CTRY,LC1,A1)/2.5;

MTINIT('2',LC1,A1) = MTFIN1('2',LC1,A1)/3;

*adjust south inventories in US
MTINIT('1','1',A1) = MTFIN1('1','1',A1)/5;
MTINIT('1','4',A1) = MTFIN1('1','4',A1)/5;
MTINIT('1','26',A1) = MTFIN1('1','26',A1)/8.5;
MTINIT('1','27',A1) = MTFIN1('1','27',A1)/8.5;
MTINIT('1','28',A1) = MTFIN1('1','28',A1)/8.5;
MTINIT('1','29',A1) = MTFIN1('1','29',A1)/8.5;
MTINIT('1','30',A1) = MTFIN1('1','30',A1)/8.5;
MTINIT('1','31',A1) = MTFIN1('1','31',A1)/8.5;
MTINIT('1','32',A1) = MTFIN1('1','32',A1)/8.5;

*******************************************************************************
* CHANGED LIMROW AND LIMCOL TO SHOW EQUATIONS IN LIST FILE (PRIOR, BOTH = 0)
*******************************************************************************
OPTION LIMROW = 5,
      LIMCOL =  3 ;

OPTION ITERLIM = 50000000;
OPTION RESLIM = 50000000;
*OPTION BRATIO=1;

* Can solve using either MINOS or CONOPT but recommend MINOS for this formulation
OPTION NLP= MINOS;
OPTION DOMLIM=1000000;
*OPTION SYSOUT = ON;
*OPTION PROFILE =3;
*OPTION DMPSYM;

$ontext;
MODEL DYNFONLYM / MOTION11, MOTSIN11, MOTIN11, MOTRPSIN1, MOTRPSIN2,MOTRPIN1,
MOTION21, MOTION11BIO, MOTION21BIO, REPSLIN1, REPDEDBIO, MAXFOR, MAXFORCTRY,  HARVEST1,HARVSIN1,HARVIN1,
HARVSIN2,HARVIN2, HARVEST1BIO , CUMAC1 ,TCHARV1,TCHARV2, BENFOR1, TFORESTAREA 
/;
$offtext;



*set upper and lower bounds on management intensity
IMGMT1.LO(CTRY,LC1,T) = MTFIN1(CTRY,LC1,'1')*0;
IMGMT1.UP(CTRY,LC1,T) = MTFIN1(CTRY,LC1,'1')*4;
MGMT1.LO(CTRY,LC1,A1,T) = MTFIN1(CTRY,LC1,'1')*0;
MGMT1.UP(CTRY,LC1,A1,T) = MTFIN1(CTRY,LC1,'1')*4;

YACRE2.LO(CTRY,LC1,A1,T) = FORINV2(CTRY,LC1,A1)*0;
YACRE2.UP(CTRY,LC1,A1,T) = 10000;

TOTALFOREST.L(T) = SUM(CTRY,SUM(LC1,SUM(A1,
         YACRE2.L(CTRY,LC1,A1,T)$(R1FOR(CTRY,LC1) EQ 1)+
         YACRE2.L(CTRY,LC1,A1,T)$(TEMPINAC(CTRY,LC1) EQ 1)+
         YACRE2.L(CTRY,LC1,A1,T)$(TROPINAC(CTRY,LC1) EQ 1)+
         YACRE3.L(CTRY,LC1,A1,T)$(TROPINAC(CTRY,LC1) EQ 1)+
         YACRIN1.L(CTRY,LC1,A1,T)$(TEMPINAC(CTRY,LC1) EQ 1)+
         YACRIN1.L(CTRY,LC1,A1,T)$(TROPINAC(CTRY,LC1) EQ 1))
));

DYNFONLYM.WORKSPACE = 900;

DYNFONLYM.OPTFILE = 1;
DYNFONLYM.SCALEOPT= 1;

MGMT1.SCALE(CTRY,LC1,A1,T)=10;

BENFOR1.SCALE =10000000;
NPVFOR1.SCALE =10000000;

* PLACES ALL OUTPUT TO A GDX FILE
* redo this at end

execute_unload "GTM_2020_R2.gdx";


DYNFONLYM.reslim = 60*10;
SOLVE DYNFONLYM USING NLP MAXIMIZING NPVFOR1;

PARAMETER RENTACC(CTRY,LC1,T);
RENTACC(CTRY,LC1,T)$(ALLIN(CTRY,LC1) EQ 1)=
-RENTZ(CTRY,LC1,T) +
RENTA(CTRY,LC1,T)*{[SUM(A1,YACRE2.L(CTRY,LC1,A1,T) + YACRE3.L(CTRY,LC1,A1,T) +
YACRIN1.L(CTRY,LC1,A1,T))+ EPSILON]**(1/RENTB(CTRY,LC1))}

PARAMETER RENTAMT(CTRY,LC1,T);
RENTAMT(CTRY,LC1,T)$(TROPINAC(CTRY,LC1) EQ 1) =
*inaccessible forests tropical zone
-RENTZ(CTRY,LC1,T)*
[SUM(A1,YACRE2.L(CTRY,LC1,A1,T) +YACRE3.L(CTRY,LC1,A1,T) +YACRIN1.L(CTRY,LC1,A1,T))+EPSILON]+
{1/((1/RENTB(CTRY,LC1))+1)}*RENTA(CTRY,LC1,T)*
[SUM(A1,YACRE2.L(CTRY,LC1,A1,T) +YACRE3.L(CTRY,LC1,A1,T) +YACRIN1.L(CTRY,LC1,A1,T))+EPSILON]**{(1/RENTB(CTRY,LC1))+1}
-
*subtract out negative part
(
-RENTZ(CTRY,LC1,T)*[RENTHA(CTRY,LC1,T)]+
{1/((1/RENTB(CTRY,LC1))+1)}*RENTA(CTRY,LC1,T)*
        [RENTHA(CTRY,LC1,T)+EPSILON]**{(1/RENTB(CTRY,LC1))+1}
);

DISPLAY RENTACC, RENTAMT;

PARAMETER RENTTOTAL(CTRY,LC1,T);
RENTTOTAL(CTRY,LC1,T) =
*inaccessible forests tropical zone
-RENTZ(CTRY,LC1,T)*
[SUM(A1,YACRE2.L(CTRY,LC1,A1,T) +YACRE3.L(CTRY,LC1,A1,T) +YACRIN1.L(CTRY,LC1,A1,T))+EPSILON]+
{1/((1/RENTB(CTRY,LC1))+1)}*RENTA(CTRY,LC1,T)*
[SUM(A1,YACRE2.L(CTRY,LC1,A1,T) +YACRE3.L(CTRY,LC1,A1,T) +YACRIN1.L(CTRY,LC1,A1,T))+EPSILON]**{(1/RENTB(CTRY,LC1))+1}

-
*subtract out negative part
(
-RENTZ(CTRY,LC1,T)*[RENTHA(CTRY,LC1,T)]+
{1/((1/RENTB(CTRY,LC1))+1)}*RENTA(CTRY,LC1,T)*
        [RENTHA(CTRY,LC1,T)+EPSILON]**{(1/RENTB(CTRY,LC1))+1}
);

PARAMETER RENTTOTALCTRY(CTRY,T);
RENTTOTALCTRY(CTRY,T) = SUM(LC1,RENTTOTAL(CTRY,LC1,T));


* PLACES ALL OUTPUT TO A GDX FILE
* redo this at end
execute_unload "GTM_2020_R2.gdx";


$ONTEXT;
The rest of the file creates output and puts it into a set of tables that are placed into a PUT file
Which can be imported directly into Excel.  

Carbon calculations are also provided below.
$OFFTEXT;



*quantity of sawtimber harvested by region
PARAMETER QFS(CTRY,T);
QFS(CTRY,T) =


*accessible timber - with proportion going to Biomass
SUM[LC1$(R1FOR(CTRY,LC1) EQ 1),
SUM(A1,(1-PROPPULP.L(CTRY,LC1,T))*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+

* Temperate semi-inaccessible
SUM[LC1$(TEMPINAC(CTRY,LC1) EQ 1),

SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+
*******************************************************************************
*temperate inacessible - harvest at the average age of the old stuff
* harvest average timber age; the 0.6 is the merchantable proportion.
SUM[LC1$(TEMPINAC(CTRY,LC1) EQ 1),
        (1-PROPPULP.L(CTRY,LC1,T))*PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)*
        YLDINAC(CTRY,LC1,A1,T))]+

*tropical semi-inaccessible
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+

*tropical low harvest
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR3.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*0.5*PARAM2(CTRY,LC1,'8'))]+

*tropical inacessible - harvest
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        (1-PROPPULP.L(CTRY,LC1,T))*
PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)* YLDINAC(CTRY,LC1,A1,T))]
;

*quantity of sawtimber harvested by region and land class
PARAMETER QFSLC(CTRY,LC1,T);
QFSLC(CTRY,LC1,T) =

*accessible timber - with proportion going to Biomass
[SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(R1FOR(CTRY,LC1) EQ 1)+

* Temperate semi-inaccessible
[SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(TEMPINAC(CTRY,LC1) EQ 1)+
*******************************************************************************
*temperate inacessible - harvest at the average age of the old stuff
* harvest average timber age; the 0.6 is the merchantable proportion.
[(1-PROPPULP.L(CTRY,LC1,T))*PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)*
        YLDINAC(CTRY,LC1,A1,T))]$(TEMPINAC(CTRY,LC1) EQ 1)+

*tropical semi-inaccessible
[SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(TROPINAC(CTRY,LC1) EQ 1)+

*tropical low harvest
[SUM(A1, (1-PROPPULP.L(CTRY,LC1,T))*
ACHR3.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*0.5*PARAM2(CTRY,LC1,'8'))] $(TROPINAC(CTRY,LC1) EQ 1)+

*tropical inacessible - harvest
[(1-PROPPULP.L(CTRY,LC1,T))*
PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)* YLDINAC(CTRY,LC1,A1,T))] $(TROPINAC(CTRY,LC1) EQ 1)
;

*quantity of sawtimber harvested globally
PARAMETER TAFS(T);
TAFS(T) = SUM(CTRY,QFS(CTRY ,T));

*global price of sawtimber 
PARAMETER FPS(T);
FPS(T) = (1/1)*{AFS(T)**(1/BF)}*{(TAFS(T)+EPSILON)**(-1/BF)};

DISPLAY QFS, TAFS, FPS;

*quantity of pulpwood harvested regionally
PARAMETER QFP(CTRY,T);
QFP(CTRY,T) =


*accessible timber - with proportion going to Biomass
SUM[LC1$(R1FOR(CTRY,LC1) EQ 1),
SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+

* Temperate semi-inaccessible
SUM[LC1$(TEMPINAC(CTRY,LC1) EQ 1),

SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+
*******************************************************************************
*temperate inacessible - harvest at the average age of the old stuff
* harvest average timber age; the 0.6 is the merchantable proportion.
SUM[LC1$(TEMPINAC(CTRY,LC1) EQ 1),
        PROPPULP.L(CTRY,LC1 ,T)*
        PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)*
        YLDINAC(CTRY,LC1,A1,T))]+

*tropical semi-inaccessible
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+

*tropical low harvest
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
        ACHR3.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*0.5*PARAM2(CTRY,LC1,'8'))]+

*tropical inacessible - harvest
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        PROPPULP.L(CTRY,LC1 ,T)*PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)* YLDINAC(CTRY,LC1,A1,T))]
;

*quantity of sawtimber harvested regionally and by land class
PARAMETER QFPLC(CTRY,LC1,T);
QFPLC(CTRY,LC1,T) =

*accessible timber - with proportion going to Biomass
[SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(R1FOR(CTRY,LC1) EQ 1)+

* Temperate semi-inaccessible
[SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(TEMPINAC(CTRY,LC1) EQ 1)+
*******************************************************************************
*temperate inacessible - harvest at the average age of the old stuff
* harvest average timber age; the 0.6 is the merchantable proportion.
[        PROPPULP.L(CTRY,LC1 ,T)*
        PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)*
        YLDINAC(CTRY,LC1,A1,T))]$(TEMPINAC(CTRY,LC1) EQ 1)+

*tropical semi-inaccessible
[SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))] $(TROPINAC(CTRY,LC1) EQ 1)+

*tropical low harvest
[SUM(A1, PROPPULP.L(CTRY,LC1 ,T)*
        ACHR3.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*0.5*PARAM2(CTRY,LC1,'8'))] $(TROPINAC(CTRY,LC1) EQ 1)+

*tropical inacessible - harvest
[PROPPULP.L(CTRY,LC1 ,T)*PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)* YLDINAC(CTRY,LC1,A1,T))]$(TROPINAC(CTRY,LC1) EQ 1)
;

*quantity of pulpwood harvested globally
PARAMETER TAFP(T);
TAFP(T) = SUM(CTRY,QFP(CTRY ,T));

*global price of pulpwood
PARAMETER FPP(T);
FPP(T) = {AFP(T)**(1/BF)}*{((TAFP(T)/PULPADJUST)+EPSILON)**(-1/BF)};

DISPLAY QFS, TAFS, FPS, QFP, TAFP, FPP;

*timber harvested in accessible forest types by region
PARAMETER QFACCESS(CTRY,T);
QFACCESS(CTRY,T) =
***********************************************************************
*accessible timber for roundwood
SUM[LC1$(R1FOR(CTRY,LC1) EQ 1),
SUM(A1, ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))];

*accessible timber for bioenergy
PARAMETER QBACCESS(CTRY,T);
QBACCESS(CTRY,T) =

SUM[LC1$(R1FOR(CTRY,LC1) EQ 1),
SUM(A1, ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))];
***********************************************************************
***********************************************************************
PARAMETER QFTEMPINAC(CTRY,T);
QFTEMPINAC(CTRY,T) =
*temperate semi-inaccessible
SUM[LC1$(TEMPINAC(CTRY,LC1) EQ 1),
SUM(A1, ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+
***********************************************************************
*temperate inaccessible - harvest 50 years of age
SUM[LC1$(TEMPINAC(CTRY,LC1) EQ 1),
        PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)*
       YIELD2(CTRY,LC1,A1,T))];
***********************************************************************
PARAMETER QFTROPINAC(CTRY,T);
QFTROPINAC(CTRY,T) =
*tropical semi-inaccessible
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1,ACHR2.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]+
*tropical low harvest
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1,ACHR3.L(CTRY,LC1,A1,T)*YIELD2(CTRY,LC1,A1,T)*0.5*PARAM2(CTRY,LC1,'8'))]+
*tropical inacessible - harvest 50 years of age
SUM[LC1$(TROPINAC(CTRY,LC1) EQ 1),
        PARAM2(CTRY,LC1,'8')*SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)*YLDINAC(CTRY,LC1,A1,T))]
;


PARAMETER TEMPINACHA(CTRY ,T);
TEMPINACHA(CTRY ,T) = SUM(LC1$(TEMPINAC(CTRY,LC1) EQ 1),
        SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)));

PARAMETER TEMPSEMIACHA(CTRY ,T);
TEMPSEMIACHA(CTRY ,T) = SUM(LC1$(TEMPINAC(CTRY,LC1) EQ 1),
        SUM(A1,YACRE2.L(CTRY,LC1,A1,T)));

PARAMETER TROPINACHA(CTRY ,T);
TROPINACHA(CTRY ,T) = SUM(LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)));

PARAMETER TROPSEMIACHA(CTRY ,T);
TROPSEMIACHA(CTRY ,T) = SUM(LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1,YACRE2.L(CTRY,LC1,A1,T)))+
 SUM(LC1$(TROPINAC(CTRY,LC1) EQ 1),
        SUM(A1,YACRE3.L(CTRY,LC1,A1,T)));

PARAMETER SUBTRPLT(CTRY,T);
SUBTRPLT(CTRY,T)= SUM(LC1$(PARAM3(CTRY,LC1,'1') EQ 1),
        SUM(A1,YACRE2.L(CTRY,LC1,A1,T)));

PARAMETER FORACI1(CTRY,T);
FORACI1(CTRY,T) = SUM(LC1, SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)));

PARAMETER TFOREST(CTRY,T);
TFOREST(CTRY,T)= SUM(LC1,SUM(A1,YACRE2.L(CTRY,LC1,A1,T)))+ SUM(LC1,SUM(A1,YACRE3.L(CTRY,LC1,A1,T)))+
        SUM(LC1, SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)));

PARAMETER TFORESTLC(CTRY,LC1,T);
TFORESTLC(CTRY,LC1,T)= SUM(A1,YACRE2.L(CTRY,LC1,A1,T))+ SUM(A1,YACRE3.L(CTRY,LC1,A1,T)+
YACRIN1.L(CTRY,LC1 ,A1,T));

PARAMETER ALLTIMBER(T);
ALLTIMBER(T)= SUM(CTRY,
SUM(LC1,SUM(A1,YACRE2.L(CTRY,LC1,A1,T)))+ FORACI1(CTRY,T));

*******************************************************************************
*PRINT OUTPUT TO PUT FILE AND DO CARBON CALCULATIONS BELOW
*******************************************************************************

PARAMETER PANDQ(RC,T);
PANDQ(RC,T) = FPS(T)$(ORD(RC) EQ 1) + TAFS(T)$(ORD(RC) EQ 2) +
FPP(T)$(ORD(RC) EQ 3) + TAFP(T)$(ORD(RC) EQ 4);


FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT 'HARVESTS (MMm3/dec) AND PRICE (2010 US $/m3)';
PUT / 'YEAR';
PUT 'TIMBER PRICE';
PUT 'TIMBER QUANTITY';
PUT 'PULP PRICE';
PUT 'PULP QUANTITY';
PUT '';
LOOP(T, PUT / T.TE(T);LOOP(RC, PUT PANDQ(RC,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONALM SAWTIMBER HARVESTS - INCLUDING INACCESSIBLE but NOT TIMBER FOR BIOMASS (MMm3/dec)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT QFS(CTRY,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONALM PULP HARVESTS - INCLUDING INACCESSIBLE but NOT TIMBER FOR BIOMASS (MMm3/dec)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT QFP(CTRY,T)););



FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL HARVESTS - ACCESSIBLE (MMm3/dec)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT QFACCESS(CTRY,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL HARVESTS - TEMPERATE INACCESSIBLE (MMm3/dec)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT QFTEMPINAC(CTRY,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL HARVESTS - TROPICAL INACCESSIBLE (MMm3/dec)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT QFTROPINAC(CTRY,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL HECTARES -TOTAL (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TFOREST(CTRY,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL TEMPERATE INACCESSIBLE HECTARES -TOTAL (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TEMPINACHA(CTRY ,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL TEMPERATE SEMI-ACCESSIBLE HECTARES -TOTAL (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TEMPSEMIACHA(CTRY ,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL TROPICAL INACCESSIBLE HECTARES -TOTAL (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TROPINACHA(CTRY ,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL TROPICAL SEMI-ACCESSIBLE HECTARES -TOTAL (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TROPSEMIACHA(CTRY ,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL SUBTROPICAL PLANTATION HECTARES -TOTAL (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT SUBTRPLT(CTRY,T)););

PARAMETER DEDBIOAREALC(CTRY,LC1,T);
DEDBIOAREALC(CTRY,LC1,T)$(DEDBIO(CTRY,LC1) EQ 1) =
SUM(A1,YACRE2.L(CTRY,LC1,A1,T)$(DEDBIO(CTRY,LC1) EQ 1));

PARAMETER DEDBIOAREA(CTRY,T);
DEDBIOAREA(CTRY,T)=SUM(LC1,DEDBIOAREALC(CTRY,LC1,T));

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'REGIONAL DEDICATED BIOFUEL CROPS (Million)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT DEDBIOAREA(CTRY,T)););

PARAMETER QFACCUS(LC1,T);
QFACCUS(LC1,T) =

*accessible timber
SUM(A1,ACHR2.L('1',LC1,A1,T)*YIELD2('1',LC1,A1,T)*PARAM2('1',LC1,'8')*
       ((1+MGMT1.L('1',LC1,A1,T))**FINPTEL('1',LC1,T)));

PARAMETER QFINACUS(LC1,T);
QFINACUS(LC1,T) =
*temperate semi-inaccessible
SUM(A1,ACHR2.L('1',LC1,A1,T)*YIELD2('1',LC1,A1,T)*PARAM2('1',LC1,'8')*
       ((1+MGMT1.L('1',LC1,A1,T))**FINPTEL('1',LC1,T)))$(TEMPINAC('1',LC1) EQ 1)+

PARAM2('1',LC1,'8')*SUM(A1,ACHRIN1.L('1',LC1,A1,T)*YLDINAC('1',LC1,A1,T));

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US SAWTIMBER OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 26), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) LT 26), PUT QFSLC('1',LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US SAWTIMBER OUTPUT INACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 25), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 25), PUT QFSLC('1',LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US SAWTIMBER OUTPUT INACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 50), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 50), PUT QFSLC('1',LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US PULPWOOD OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 26), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) LT 26), PUT QFPLC('1',LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US PULPWOOD OUTPUT INACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 25), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 25), PUT QFPLC('1',LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US PULPWOOD OUTPUT INACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 50), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 50), PUT QFPLC('1',LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US ACCESSIBLE OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 26), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) LT 26), PUT QFACCUS(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US ACCESSIBLE OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 25), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 25), PUT QFACCUS(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US ACCESSIBLE OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 50), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 50), PUT QFACCUS(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US INACCESSIBLE OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 26), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) LT 26), PUT QFINACUS(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US INACCESSIBLE OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 25), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 25), PUT QFINACUS(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US INACCESSIBLE OUTPUT';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 50), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 50), PUT QFINACUS(LC1,T)););


*******************************************************************************
* OUTPUT HECTARES BY US FOREST TYPE
*******************************************************************************

PARAMETER TUSFORESTACC(LC1,T);
TUSFORESTACC(LC1,T)= SUM(A1,YACRE2.L('1',LC1,A1,T));

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US HECTARES BY FOREST TYPE - ACCESSIBLE (Million)';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 26), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) LT 26), PUT TUSFORESTACC(LC1,T)););

PARAMETER TUSFORESTINACC(LC1,T);
TUSFORESTINACC(LC1,T)= SUM(A1,YACRIN1.L('1',LC1,A1,T));

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US HECTARES BY FOREST TYPE - INACCESSIBLE (Million)';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 25) , PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1, PUT TUSFORESTINACC(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US HECTARES BY FOREST TYPE - INACCESSIBLE (Million)';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 50), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 50), PUT TUSFORESTINACC(LC1,T)););

PARAMETER TUSFORESTSEMACC(LC1,T);
TUSFORESTSEMACC(LC1,T)= SUM(A1,YACRE2.L('1',LC1,A1,T)$(TEMPINAC('1',LC1) EQ 1));

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US HECTARES BY FOREST TYPE - SEMI ACCESSIBLE (Million)';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 50), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1, PUT TUSFORESTSEMACC(LC1,T)););

FILE GTM_2020_R2; PUT GTM_2020_R2; GTM_2020_R2.PC=5;
PUT / 'US HECTARES IN DEDICATED BIOMASS ENERGY (Million)';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 25), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1, PUT DEDBIOAREALC('1',LC1,T)););


*******************************************************************************
*******************************************************************************
* CARBON ACCOUNTING AND CARBON OUTPUTS
*******************************************************************************
*******************************************************************************

*carbon yield functions � use original yield functions.
PARAMETER CYIELD (CTRY, LC1,A1,T) yield function;
CYIELD(CTRY,LC1,A1,T) = YIELDORIG(CTRY,LC1,A1,T);

PARAMETER CYA (CTRY,LC1,A1,T);
CYA(CTRY,LC1,A1,T) = CYIELD(CTRY,LC1,A1,T);

CYIELD(CTRY,LC1,A1,T) = CYA(CTRY,LC1,A1,T)$(ORD(A1) LT 10) + 
	CYA(CTRY,LC1,'10',T)$(ORD(A1) GT 9);

*adjust tropical plantation types so not too much accumulation beyond MSA
*****************************
PARAMETER CADJTROP(CTRY,LC1);
CADJTROP(CTRY,LC1) = 1$(ORD(CTRY) EQ 3) + 1$(ORD(CTRY) EQ 8) + 1$(ORD(CTRY) EQ 9) + 1$(ORD(CTRY) EQ 10) + 1$(ORD(CTRY) EQ 11) + 1$(ORD(CTRY) EQ 12);

CADJTROP(CTRY,LC1)=CADJTROP(CTRY,LC1)*PARAM3(CTRY,LC1,'1');

LOOP(A1,
CYIELD(CTRY,LC1,A1,T)$(CADJTROP(CTRY,LC1) EQ 1) = 
CYA(CTRY,LC1,A1,T)$(ORD(A1) LT (PARAM2(CTRY,LC1,'11')+1)) + 
	CYIELD(CTRY,LC1,A1-1,T)$(ORD(A1) GT PARAM2(CTRY,LC1,'11'))
);
*****************************

PARAMETER CYLDINAC(CTRY,LC1,A1,T);
CYLDINAC(CTRY,LC1,A1,T) = CYIELD(CTRY,LC1,A1,T)$(ORD(A1) LT 10) + 
	CYIELD(CTRY,LC1,'10',T)$(ORD(A1) GT 9);


****    Standing Timber calculated with Smith, Heath et al, for US ****
*
*       Live-tree mass density = F � (G + (1-e(-volume/H)))
*********************************************************

PARAMETER ABVCHEATH(CTRY,LC1,T);
ABVCHEATH(CTRY,LC1,T) =

0.5*
[
SUM(A1, YACRE2.L(CTRY,LC1,A1,T)*

CPARAM2(CTRY,LC1,'11')*
(
CPARAM2(CTRY,LC1,'12') +
(1-EXP(-CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))/
CPARAM2(CTRY,LC1,'13'))
)
)

)
]

+

*temperate inaccessible TYPES A &B

0.5*
[
SUM(A1,
YACRIN1.L(CTRY,LC1,A1,T)*
CPARAM2(CTRY,LC1,'11')*
(
CPARAM2(CTRY,LC1,'12') +
(1-EXP(-CYLDINAC(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')/
CPARAM2(CTRY,LC1,'13'))
)
)

)
]

+

*tropical semi-inaccessible type
[CPARAM2(CTRY,LC1,'3')*SUM(A1,YACRE2.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*
((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical low management type
[CPARAM2(CTRY,LC1,'3')*SUM(A1,YACRE3.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8'))] $(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical inaccessible type
[CPARAM2(CTRY,LC1,'3')*PARAM2(CTRY,LC1,'8')*SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)*
CYLDINAC(CTRY,LC1,A1,T))] $(TROPINAC(CTRY,LC1) EQ 1)
;

****    Standing Dead Timber calculated with Smith, Heath et al, for US ****
*
*       Live-tree mass density = F � (G + (1-e(-volume/H)))
* Dead-tree mass density = (Estimated live-tree mass density) � A � e(-((volume/B)^C))

*********************************************************

PARAMETER ABVDEADCHEATH(CTRY,LC1,T);
ABVDEADCHEATH(CTRY,LC1,T) =

0.5*
[
SUM(A1, YACRE2.L(CTRY,LC1,A1,T)*


{
CPARAM2(CTRY,LC1,'11')*
(
CPARAM2(CTRY,LC1,'12') +
(1-EXP(-CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))/
CPARAM2(CTRY,LC1,'13'))
)
)}*
CPARAM2(CTRY,LC1,'24')*
EXP(-((
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))/ CPARAM2(CTRY,LC1,'25'))**CPARAM2(CTRY,LC1,'26')))

)
]

+

*temperate inaccessible TYPES A &B

0.5*
[
SUM(A1,
YACRIN1.L(CTRY,LC1,A1,T)*

{CPARAM2(CTRY,LC1,'11')*
(
CPARAM2(CTRY,LC1,'12') +
(1-EXP(-CYLDINAC(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')/
CPARAM2(CTRY,LC1,'13'))
)
)}*
CPARAM2(CTRY,LC1,'24')*
EXP(-((
PARAM2(CTRY,LC1,'8')*CYLDINAC(CTRY,LC1,A1,T)/ CPARAM2(CTRY,LC1,'25'))**CPARAM2(CTRY,LC1,'26')))

)
]

*The calculations for tropical areas are incorrect and would need to be updated if used.
+

*tropical semi-inaccessible type
[CPARAM2(CTRY,LC1,'3')*SUM(A1,YACRE2.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*
((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical low management type
[CPARAM2(CTRY,LC1,'3')*SUM(A1,YACRE3.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8'))] $(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical inaccessible type
[CPARAM2(CTRY,LC1,'3')*PARAM2(CTRY,LC1,'8')*SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)*
CYLDINAC(CTRY,LC1,A1,T))] $(TROPINAC(CTRY,LC1) EQ 1)
;


*     *********** Standing Timber ***********
*calculated with IPCC methods per GPG for rest of world
* C = V*D*BEF*(1+R)*CF

*V = m3/ha
*D = wood density (parameter 14)
*BEF = biomass expansion factor (parameter 15)
*R = root/shoot ratio (parameter 16)
*CF= carbon % = 0.5 (parameter 17)
****************************************


PARAMETER ABVCACRGPG(CTRY,LC1,T);
ABVCACRGPG(CTRY,LC1,T) =

CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*[SUM(A1, YACRE2.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T)))] $(R1FOR(CTRY,LC1) EQ 1)
+


CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*[SUM(A1, YACRE2.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T)))] $(TEMPINAC(CTRY,LC1) EQ 1)
+

*temperate inaccessible TYPE A
[
CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*
SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T))*
PARAM2(CTRY,LC1,'8')]$(R1FOR(CTRY,LC1) EQ 1)
+

*temperate inaccessible type B
[
CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*PARAM2(CTRY,LC1,'8')*
SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)*
        CYLDINAC(CTRY,LC1,A1,T))]$(TEMPINAC(CTRY,LC1) EQ 1)
+

*tropical semi-inaccessible type
*use CYLDINAC to limit yield increases past 100
[
CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*SUM(A1,YACRE2.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*
((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))]$(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical low management type
*use CYLDINAC to limit yield increases past 100
[
CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*SUM(A1,YACRE3.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8'))] $(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical inaccessible type
*use CYLDINAC to limit yield increases past 100
 [
CPARAM2(CTRY,LC1,'14')*CPARAM2(CTRY,LC1,'15')*(1+CPARAM2(CTRY,LC1,'16'))*
CPARAM2(CTRY,LC1,'17')*PARAM2(CTRY,LC1,'8')*
SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T))] $(TROPINAC(CTRY,LC1) EQ 1)
;


**** Standing Timber calculated with Smith, Heath et al, for US ****
*       calculated for each age class
*       Live-tree mass density = F � (G + (1-e(-volume/H)))
*********************************************************

PARAMETER ABVCHEATHAGE(CTRY,LC1,A1,T);
ABVCHEATHAGE(CTRY,LC1,A1,T) =

0.5*
[
 YACRE2.L(CTRY,LC1,A1,T)*

CPARAM2(CTRY,LC1,'11')*
(
CPARAM2(CTRY,LC1,'12') +
(1-EXP(-CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))/
CPARAM2(CTRY,LC1,'13'))
)
)
]



+
*temperate inaccessible TYPES A & b
0.5*
[
YACRIN1.L(CTRY,LC1,A1,T)*

CPARAM2(CTRY,LC1,'11')*
(
CPARAM2(CTRY,LC1,'12') +
(
1-EXP(-CYLDINAC(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')/
CPARAM2(CTRY,LC1,'13'))
)
)
]$(ORD(A1) EQ CARD(A1))

;

PARAMETER ABVHEATHBYHA(CTRY,LC1,A1,T);
ABVHEATHBYHA(CTRY,LC1,A1,T) =
ABVCHEATHAGE(CTRY,LC1,A1,T)/(
YACRE2.L(CTRY,LC1,A1,T)+YACRIN1.L(CTRY,LC1,A1,T)+EPSILON);



*     *********** Standing Timber ***********

* aboveground carbon
* calculated the original way

****************************************


PARAMETER ABVCACRAGE(CTRY,LC1,A1,T);
ABVCACRAGE(CTRY,LC1,A1,T) =

CPARAM2(CTRY,LC1,'3')*[YACRE2.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))] $(R1FOR(CTRY,LC1) EQ 1)
+

*tropical semi-inaccessible type
[CPARAM2(CTRY,LC1,'3')*YACRE2.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*
((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T))]$(TROPINAC(CTRY,LC1) EQ 1)
+

*tropical low management type
[CPARAM2(CTRY,LC1,'3')*YACRE3.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')] $(TROPINAC(CTRY,LC1) EQ 1)
;



*******************************************************************************
*Litter
*******************************************************************************

R1FOR(CTRY,'24') =0;

PARAMETER LITTERACCAGE(CTRY,LC1,A1,T);
LITTERACCAGE(CTRY,LC1,A1,T)$(R1FOR(CTRY,LC1) EQ 1) = YACRE2.L(CTRY,LC1,A1,T)*CPARAM2(CTRY,LC1,'28')*
[CYIELD(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,A1,T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))]/
[EPSILON+CYIELD(CTRY,LC1,'15',T)*PARAM2(CTRY,LC1,'8')*((MGMT1.L(CTRY,LC1,'15',T)+1+EPSILON)**FINPTEL(CTRY,LC1,T))]$(R1FOR(CTRY,LC1) EQ 1);

PARAMETER LITTERINACCAGE(CTRY,LC1,A1,T);
LITTERINACCAGE(CTRY,LC1,A1,T) =

{[CPARAM2(CTRY,LC1,'28')*YACRE2.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)]/
[EPSILON + CYIELD(CTRY,LC1,'15',T)]}$(TEMPINAC(CTRY,LC1) EQ 1)

+


*temperate inaccessible TYPE A
{[CPARAM2(CTRY,LC1,'28')*
YACRIN1.L(CTRY,LC1,A1,T)*CYLDINAC(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')]/[EPSILON+CYLDINAC(CTRY,LC1,'15',T)]}$(R1FOR(CTRY,LC1) EQ 1)
+

*temperate inaccessible type B
{[CPARAM2(CTRY,LC1,'28')*PARAM2(CTRY,LC1,'8')*
YACRIN1.L(CTRY,LC1,A1,T)*
        CYLDINAC(CTRY,LC1,A1,T)]/[EPSILON+YLDINAC(CTRY,LC1,'15',T)]}$(TEMPINAC(CTRY,LC1) EQ 1);



PARAMETER LITTERSUMLC(CTRY,LC1,T);
LITTERSUMLC(CTRY,LC1,T) = SUM(A1,LITTERACCAGE(CTRY,LC1,A1,T)+ LITTERINACCAGE(CTRY,LC1,A1,T));

PARAMETER LITTERSUM(CTRY,T);
LITTERSUM(CTRY,T) = SUM(LC1,LITTERSUMLC(CTRY,LC1,T));



*******************************************************************************
* total aboveground carbon using Heath estimates for US and IPCC GPG for rest of world
*******************************************************************************



PARAMETER TABVCR(CTRY,T);
TABVCR(CTRY,T)=SUM(LC1, ABVCHEATH(CTRY,LC1,T)$(ORD(CTRY) EQ 1) +
                               ABVCACRGPG(CTRY,LC1,T)$(ORD(CTRY) GT 1));

PARAMETER TABVCRDEAD(CTRY,T);
TABVCRDEAD(CTRY,T)=SUM(LC1, ABVDEADCHEATH(CTRY,LC1,T)$(ORD(CTRY) EQ 1) +
                ABVCACRGPG(CTRY,LC1,T)*CPARAM2(CTRY,LC1,'27')$(ORD(CTRY) GT 1));


PARAMETER TABVCLIVEANDDEAD(CTRY,T);
TABVCLIVEANDDEAD(CTRY,T)= TABVCR(CTRY,T)+ TABVCRDEAD(CTRY,T);

*allocate US estimates to regions in US for reporting purposes.
PARAMETER TABVUS(DATA,T);
TABVUS('1',T)= SUM(LC1,(ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(ORD(LC1) LT 26));
TABVUS('2',T)= SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(ORD(LC1) LT 59))-TABVUS('1',T);
TABVUS('3',T)= SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(ORD(LC1) GT 58));


PARAMETER SOUTH(T);
PARAMETER NORTH(T);
PARAMETER PNW(T);
PARAMETER WEST(T);
PARAMETER AK(T);
PARAMETER OTHER(T);


SOUTH(T) = SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(PARAM3('1',LC1,'21') EQ 1));
NORTH(T) = SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(PARAM3('1',LC1,'21') EQ 2));
PNW(T) = SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(PARAM3('1',LC1,'21') EQ 3));
WEST(T) = SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(PARAM3('1',LC1,'21') EQ 4));
AK(T) = SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(PARAM3('1',LC1,'21') EQ 5));
OTHER(T) = SUM(LC1, (ABVCHEATH('1',LC1,T)+ ABVDEADCHEATH('1',LC1,T))$(PARAM3('1',LC1,'21') EQ 6));

TABVUS('5',T)=SOUTH(T);
TABVUS('6',T)=NORTH(T);
TABVUS('7',T)=PNW(T);
TABVUS('8',T)=WEST(T);
TABVUS('9',T)=AK(T);
TABVUS('10',T)=OTHER(T);



*******************************************************************************
*Harvested Timber
*******************************************************************************

PARAMETER MKTC(CTRY,LC1,T);
MKTC(CTRY,LC1,T)=
QFPLC(CTRY,LC1,T)*CPARAM2(CTRY,LC1,'4') +
QFSLC(CTRY,LC1,T)*CPARAM2(CTRY,LC1,'4');


*total market carbon
PARAMETER TMKTC(CTRY,T);
TMKTC(CTRY,T)=SUM(LC1, MKTC(CTRY,LC1,T));


*******************************************************************************
* Slash pool
* Calculate what remains on site after removal of harvested material
*ANNSLASHC = annual additions to slash pool
*SLASHCPOOL = slash pool
*Slash decay rate is region specific using CPARAM2(data=9)
*******************************************************************************

*annual slash contribution
PARAMETER ANNSLASHC(CTRY,LC1,T);
ANNSLASHC(CTRY,LC1,T)=
MKTC(CTRY,LC1,T)*CPARAM2(CTRY,LC1,'23');

*accumulate historical slash pool for initial slash quantity
PARAMETER INITSLASHCPOOL(CTRY,LC1,TS);
PARAMETER INITSLASHC(CTRY,LC1);

INITSLASHCPOOL(CTRY,LC1,'1') = ANNSLASHC(CTRY,LC1,'1');
INITSLASHC(CTRY,LC1)= ANNSLASHC(CTRY,LC1,'1');

LOOP(TS, INITSLASHCPOOL(CTRY,LC1,TS+1)= INITSLASHC(CTRY,LC1) + INITSLASHCPOOL(CTRY,LC1,TS)-
10*CPARAM2(CTRY,LC1,'9')*INITSLASHCPOOL(CTRY,LC1,TS));

DISPLAY INITSLASHCPOOL;

PARAMETER SLASHCPOOL(CTRY,LC1,T);
SLASHCPOOL(CTRY,LC1,'1') = INITSLASHCPOOL(CTRY,LC1,'15');
LOOP(T,SLASHCPOOL(CTRY,LC1,T+1)= ANNSLASHC(CTRY,LC1,T) + SLASHCPOOL(CTRY,LC1,T) - 10*CPARAM2(CTRY,LC1,'9')*SLASHCPOOL(CTRY,LC1,T));

PARAMETER SLASHCPOOL2(CTRY,T);
SLASHCPOOL2(CTRY,T) = SUM(LC1,SLASHCPOOL(CTRY,LC1,T));

PARAMETER ANNSLASHCCTRY(CTRY,T);
ANNSLASHCCTRY(CTRY,T) = SUM(LC1, ANNSLASHC(CTRY,LC1,T));

PARAMETER ANNRESCTRY(CTRY,T);
*ANNRESCTRY(CTRY,T) = SUM(LC1,SUM(A1,CPARAM2(CTRY,LC1,'4')*RES.L(CTRY,LC1,A1,T)));
ANNRESCTRY(CTRY,T) = 0;

$ONTEXT;
Set up storage in wood products pool.  Start by initializing stock from historical storage.
$OFFTEXT;

PARAMETER INITPULPCPOOL(CTRY,LC1,TS);
INITPULPCPOOL(CTRY,LC1,'1') =0;

PARAMETER INITPULPC(CTRY,LC1);
INITPULPC(CTRY,LC1) = CPARAM2(CTRY,LC1,'4')*(1-CPARAM2(CTRY,LC1,'20'))*QFPLC(CTRY,LC1,'1');

LOOP(TS, INITPULPCPOOL(CTRY,LC1,TS)= INITPULPC(CTRY,LC1)+
INITPULPCPOOL(CTRY,LC1,TS-1)-
10*CPARAM2(CTRY,LC1,'21')*INITPULPCPOOL(CTRY,LC1,TS-1));


PARAMETER PULPSTORE(CTRY,LC1,T);
PULPSTORE(CTRY,LC1,'1') = INITPULPCPOOL(CTRY,LC1,'15');

LOOP(T, PULPSTORE(CTRY,LC1,T+1) = PULPSTORE(CTRY,LC1,T) +
CPARAM2(CTRY,LC1,'4')*(1-CPARAM2(CTRY,LC1,'20'))*QFPLC(CTRY,LC1,T)
- 10*CPARAM2(CTRY,LC1,'21')*PULPSTORE(CTRY,LC1,T));


*SET UP STORAGE OF C STOCK IN WOOD PRODUCTS FOR SOLIDWOOD
PARAMETER INITSOLIDCPOOL(CTRY,LC1,TS);
INITSOLIDCPOOL(CTRY,LC1,'1') =0;

PARAMETER INITSOLIDC(CTRY,LC1);
INITSOLIDC(CTRY,LC1)=
CPARAM2(CTRY,LC1,'4')*(1-CPARAM2(CTRY,LC1,'20'))*QFSLC(CTRY,LC1,'1');


LOOP(TS, INITSOLIDCPOOL(CTRY,LC1,TS)= INITSOLIDC(CTRY,LC1) + INITSOLIDCPOOL(CTRY,LC1,TS-1)-
10*CPARAM2(CTRY,LC1,'22')*INITSOLIDCPOOL(CTRY,LC1,TS-1));


PARAMETER SOLIDSTORE(CTRY,LC1,T);
SOLIDSTORE(CTRY,LC1,'1') =INITSOLIDCPOOL(CTRY,LC1,'15');

LOOP(T, SOLIDSTORE(CTRY,LC1,T+1) = SOLIDSTORE(CTRY,LC1,T)+
CPARAM2(CTRY,LC1,'4')*(1-CPARAM2(CTRY,LC1,'20'))*QFSLC(CTRY,LC1,T)
- 10*CPARAM2(CTRY,LC1,'22')*SOLIDSTORE(CTRY,LC1,T));


*total annual market carbon
PARAMETER TMKTC(CTRY,T);
TMKTC(CTRY,T)=SUM(LC1, MKTC(CTRY,LC1,T));

*total stock of market carbon
PARAMETER TMKTCNEW(CTRY,T);
TMKTCNEW(CTRY,T) = SUM(LC1,PULPSTORE(CTRY,LC1,T) + SOLIDSTORE(CTRY,LC1,T));

DISPLAY TMKTC, TMKTCNEW;


*calculate soil carbon
*   ************** TEMPERATE ***************
*cumulative net change in hectares in R1FOR and type YACRE2

PARAMETER CCNAC1(CTRY,LC1,T);
CCNAC1(CTRY,LC1,'1')=0;
LOOP(T,CCNAC1(CTRY,LC1,T+1)$(R1FOR(CTRY,LC1) EQ 1) =
ACPL2.L(CTRY,LC1,T) - SUM(A1,ACHR2.L(CTRY,LC1,A1,T)+ACHRIN1.L(CTRY,LC1,A1,T))+
       CCNAC1(CTRY,LC1,T));

PARAMETER CUMNAC1(CTRY,LC1,TS,T);
CUMNAC1(CTRY,LC1,'1',T)$(R1FOR(CTRY,LC1) EQ 1) = MAX[0,CCNAC1(CTRY,LC1,T)-CCNAC1(CTRY,LC1,T-1)];
LOOP(T,CUMNAC1(CTRY,LC1,TS+1,T+1)$(R1FOR(CTRY,LC1) EQ 1) = CUMNAC1(CTRY,LC1,TS,T)) ;

DISPLAY CCNAC1, CUMNAC1;

PARAMETER SOLC1(CTRY,LC1,TS);
SOLC1(CTRY,LC1,TS)=0;
SOLC1(CTRY,LC1,'1')$(R1FOR(CTRY,LC1) EQ 1) = CPARAM2(CTRY,LC1,'6');

DISPLAY SOLC1;

LOOP(TS,SOLC1(CTRY,LC1,TS+1)$(R1FOR(CTRY,LC1) EQ 1) =
SOLC1(CTRY,LC1,TS)*CPARAM2(CTRY,LC1,'7')*[(CPARAM2(CTRY,LC1,'5')-SOLC1(CTRY,LC1,TS))/SOLC1(CTRY,LC1,TS)]+SOLC1(CTRY,LC1,TS));

DISPLAY SOLC1;

PARAMETER SOLCC1(CTRY,LC1,TS,T);
SOLCC1(CTRY,LC1,TS,T)$(R1FOR(CTRY,LC1) EQ 1) =
(SOLC1(CTRY,LC1,TS)-CPARAM2(CTRY,LC1,'6'))*CUMNAC1(CTRY,LC1,TS,T);

DISPLAY SOLCC1;

PARAMETER SOILC1(CTRY,LC1,T);
SOILC1(CTRY,LC1,T)$(R1FOR(CTRY,LC1) EQ 1) = SUM(TS,SOLCC1(CTRY,LC1,TS,T));

DISPLAY SOILC1;

*count lost carbon in land lost, count only the NPV of lost carbon
PARAMETER CSOILR1(CTRY,LC1,T);
CSOILR1(CTRY,LC1,T)$(R1FOR(CTRY,LC1) EQ 1) = CPARAM2(CTRY,LC1,'5')*SUM(A1,FORINV2(CTRY,LC1,A1))+
SOILC1(CTRY,LC1,T)+
CPARAM2(CTRY,LC1,'8')*MIN[CCNAC1(CTRY,LC1,T),0];

DISPLAY CSOILR1;

*  ********* TEMPERATE TYPE B *********************
*cumulative net change in hectares in TEMPINAC and type B inaccessible temperate, YACRIN
PARAMETER CSOILT1(CTRY,LC1,T);
CSOILT1(CTRY,LC1,T)$(TEMPINAC(CTRY,LC1) EQ 1) =
CPARAM2(CTRY,LC1,'5')*(SUM(A1,YACRE2.L(CTRY,LC1,A1,T)+YACRIN1.L(CTRY,LC1,A1,T)))



*  ******* TROPICAL SEMI-ACCESSIBLE ******************
*cumulative net change in hectares in TROPINAC and type YACRE2, ACPL6
*YACRE3 AND ACPL5, IFORIN2, YACRIN2

PARAMETER CCNAC1(CTRY,LC1,T);
CCNAC1(CTRY,LC1,'1')=0;
LOOP(T,CCNAC1(CTRY,LC1,T+1)$(TROPINAC(CTRY,LC1) EQ 1) =
ACPL6.L(CTRY,LC1,T)+ ACPL5.L(CTRY,LC1,T)-
SUM(A1,ACHR2.L(CTRY,LC1,A1,T))- SUM(A1,ACHR3.L(CTRY,LC1,A1,T))-
SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T))
+CCNAC1(CTRY,LC1,T));

PARAMETER CUMNAC1(CTRY,LC1,TS,T);
CUMNAC1(CTRY,LC1,'1',T)$(TROPINAC(CTRY,LC1) EQ 1) = MAX[0,CCNAC1(CTRY,LC1,T)-CCNAC1(CTRY,LC1,T-1)];
LOOP(T,CUMNAC1(CTRY,LC1,TS+1,T+1)$(TROPINAC(CTRY,LC1) EQ 1) = CUMNAC1(CTRY,LC1,TS,T)) ;

DISPLAY CCNAC1, CUMNAC1;

PARAMETER SOLC1(CTRY,LC1,TS);
SOLC1(CTRY,LC1,TS)=0;
SOLC1(CTRY,LC1,'1')$(TROPINAC(CTRY,LC1) EQ 1) = CPARAM2(CTRY,LC1,'6');

DISPLAY SOLC1;

LOOP(TS,SOLC1(CTRY,LC1,TS+1)$(TROPINAC(CTRY,LC1) EQ 1) =
SOLC1(CTRY,LC1,TS)*CPARAM2(CTRY,LC1,'7')*[(CPARAM2(CTRY,LC1,'5')-SOLC1(CTRY,LC1,TS))/SOLC1(CTRY,LC1,TS)]+SOLC1(CTRY,LC1,TS));

DISPLAY SOLC1;

PARAMETER SOLCC1(CTRY,LC1,TS,T);
SOLCC1(CTRY,LC1,TS,T)$(TROPINAC(CTRY,LC1) EQ 1) =
(SOLC1(CTRY,LC1,TS)-CPARAM2(CTRY,LC1,'6'))*CUMNAC1(CTRY,LC1,TS,T);

DISPLAY SOLCC1;

PARAMETER SOILC1(CTRY,LC1,T);
SOILC1(CTRY,LC1,T)$(TROPINAC(CTRY,LC1) EQ 1) = SUM(TS,SOLCC1(CTRY,LC1,TS,T));

DISPLAY SOILC1;

*count lost carbon in land lost, count only the NPV of lost carbon
PARAMETER CSOILTROP1(CTRY,LC1,T);
CSOILTROP1(CTRY,LC1,T)$(TROPINAC(CTRY,LC1) EQ 1) =
CPARAM2(CTRY,LC1,'5')*SUM(A1,IFORIN2(CTRY,LC1,A1))+
SOILC1(CTRY,LC1,T)+
CPARAM2(CTRY,LC1,'8')*MIN[CCNAC1(CTRY,LC1,T),0];

DISPLAY CSOILTROP1;

PARAMETER TSOIL1(CTRY,T);
TSOIL1(CTRY,T) = SUM(LC1,CSOILR1(CTRY,LC1,T))+
SUM(LC1,CSOILT1(CTRY,LC1,T))+
SUM(LC1,CSOILTROP1(CTRY,LC1,T));

DISPLAY TSOIL1;


FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL ABOVEGROUND C -TOTAL (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TABVCLIVEANDDEAD(CTRY,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL MARKET C -TOTAL (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TMKTCNEW(CTRY,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL SOIL C -TOTAL (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TSOIL1(CTRY,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL SLASH POOL C -TOTAL (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT SLASHCPOOL2(CTRY,T)););

PARAMETER TOTALCSTORED(CTRY,T);
TOTALCSTORED(CTRY,T)=
TABVCR(CTRY,T)+
TMKTCNEW(CTRY,T)+
TSOIL1(CTRY,T)+
SLASHCPOOL2(CTRY,T);


FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL TOTAL CARBON STORAGE ALL POOLS (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TOTALCSTORED(CTRY,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL ANNUAL SLASH CONTRIBUTION C -TOTAL (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT ANNSLASHCCTRY(CTRY,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL ANNUAL RESIDUE REMOVAL C -TOTAL (million tons C)';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT ANNRESCTRY(CTRY,T)););

PARAMETER GSV1(CTRY,LC1,A1,T) accessible and semi-accessible ;
GSV1(CTRY,LC1,A1,T) = CYIELD(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       {(1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)}*
       [YACRE2.L(CTRY,LC1,A1,T)];

*GSV1(CTRY,LC1,A1,T) = CYIELD(CTRY,LC1,A1,T)*YACRE2.L(CTRY,LC1,A1,T);


PARAMETER GSV2(CTRY,LC1,T) inaccessible timber in temperate and tropical zone ;
GSV2(CTRY,LC1,T)=
*temperate inaccessible in TYPE A
[PARAM2(CTRY,LC1,'8')*
SUM(A1, CYLDINAC(CTRY,LC1,A1,T)*YACRIN1.L(CTRY,LC1,A1,T))]$(R1FOR(CTRY,LC1) EQ 1)+

*temperate inaccessible in TYPE B
[PARAM2(CTRY,LC1,'8')*
SUM(A1, CYLDINAC(CTRY,LC1,A1,T)*
        YACRIN1.L(CTRY,LC1,A1,T))]$(TEMPINAC(CTRY,LC1) EQ 1)+

*tropical low management type
[SUM(A1,YACRE3.L(CTRY,LC1,A1,T)*CYIELD(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8'))]$(TROPINAC(CTRY,LC1) EQ 1)+

[PARAM2(CTRY,LC1,'8')*SUM(A1,YACRIN1.L(CTRY,LC1,A1,T)
        *CYLDINAC(CTRY,LC1,A1,T))]$(TROPINAC(CTRY,LC1) EQ 1);

PARAMETER GSVLC(CTRY,LC1,T);
GSVLC(CTRY,LC1,T) = SUM(A1,GSV1(CTRY,LC1,A1,T))+GSV2(CTRY,LC1,T);


PARAMETER GSV(CTRY,T);
GSV(CTRY,T) = SUM(LC1,SUM(A1,GSV1(CTRY,LC1,A1,T))+GSV2(CTRY,LC1,T));


PARAMETER CGSVPHECTARELC(CTRY,LC1, T);
CGSVPHECTARELC(CTRY,LC1,T)= (SUM(A1,GSV1(CTRY,LC1,A1,T))+GSV2(CTRY,LC1,T))/
        (SUM(A1,YACRE2.L(CTRY,LC1,A1,T)+ YACRIN1.L(CTRY,LC1,A1,T)
        + YACRIN1.L(CTRY,LC1,A1,T)+ YACRE3.L(CTRY,LC1,A1,T)+EPSILON));


PARAMETER STOCKINGDENLC(CTRY,LC1,A1,T);
STOCKINGDENLC(CTRY,LC1,A1,T) = PARAM2(CTRY,LC1,'8')*
       {(1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)};


PARAMETER AREAHARVESED(CTRY,LC1,T);
AREAHARVESED(CTRY,LC1,T)= SUM(A1,ACHR2.L(CTRY,LC1,A1,T)+ ACHRIN1.L(CTRY,LC1,A1,T) + ACHR3.L(CTRY,LC1,A1,T));

PARAMETER TOTALQLC(CTRY,LC1,T);
TOTALQLC(CTRY,LC1,T) = QFSLC(CTRY,LC1,T)+QFPLC(CTRY,LC1,T);

PARAMETER QPERHA(CTRY,LC1,T);
QPERHA(CTRY,LC1,T)=TOTALQLC(CTRY,LC1,T)/(AREAHARVESED(CTRY,LC1,T)+EPSILON);


FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL GROWING STOCK VOLUME';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT GSV(CTRY,T)););


FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'US GSVACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) LT 26), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) LT 26), PUT GSVLC('1',LC1,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'US GSV INACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 32), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 32), PUT GSVLC('1',LC1,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'US GSV INACCESSIBLE';
PUT / 'YEAR'; LOOP(LC1$(ORD(LC1) GT 58), PUT LC1.TE(LC1););
LOOP(T, PUT / T.TE(T); LOOP(LC1$(ORD(LC1) GT 58), PUT GSVLC('1',LC1,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'US ABOVEC';
PUT / 'YEAR'; LOOP(DATA$(ORD(DATA) LT 26), PUT DATA.TE(DATA););
LOOP(T, PUT / T.TE(T); LOOP(DATA$(ORD(DATA) LT 26), PUT TABVUS(DATA,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL LITER Tg C VOLUME';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT LITTERSUM(CTRY,T)););

PARAMETER GSVUSTYPE(DATA ,T);
GSVUSTYPE('1' ,T)=SUM(LC1$(ORD(LC1) LT 26), GSVLC('1',LC1,T));
GSVUSTYPE('2' ,T)=SUM(LC1$(ORD(LC1) GT 32), GSVLC('1',LC1,T))- SUM(LC1$(ORD(LC1) GT 58), GSVLC('1',LC1,T));
GSVUSTYPE('3' ,T)= SUM(LC1$(ORD(LC1) GT 58), GSVLC('1',LC1,T));

PARAMETER GSVGROWTHUSTYPE(DATA ,T);
GSVGROWTHUSTYPE('1',T)$(ORD(T) LT 20) =(LOG(GSVUSTYPE('1',T+1)/ GSVUSTYPE('1',T))/10); 
GSVGROWTHUSTYPE('2',T)$(ORD(T) LT 20) =(LOG(GSVUSTYPE('2',T+1)/ GSVUSTYPE('2',T))/10); 
GSVGROWTHUSTYPE('3',T)$(ORD(T) LT 20) =(LOG(GSVUSTYPE('3',T+1)/ GSVUSTYPE('3',T))/10); 

PARAMETER TABVUS2(DATA,T);
TABVUS2('1',T)= TABVUS('1',T)*(1+GSVGROWTHUSTYPE('1',T-1))**(ORD(T) -1);
TABVUS2('2',T)= TABVUS('2',T)*(1+GSVGROWTHUSTYPE('2',T-1))**(ORD(T) -1);
TABVUS2('3',T)= TABVUS('3',T)*(1+GSVGROWTHUSTYPE('3',T-1))**(ORD(T) -1);

PARAMETER TREECARB(T);
TREECARB(T) = SUM(DATA, TABVUS2(DATA,T))+LITTERSUM('1',T)+ SLASHCPOOL2('1',T);

PARAMETER TOTALCARB(T);
TOTALCARB(T) = TREECARB(T)+ TMKTCNEW('1',T)+ TSOIL1('1',T);

PARAMETER CARBONALL(DATA,T);
CARBONALL('1',T) = TREECARB(T);
CARBONALL('2',T) = TMKTCNEW('1',T);
CARBONALL('3',T) = TSOIL1('1',T);
CARBONALL('4',T) = TOTALCARB(T);

**************************************************************************
******* Investment Costs
**************************************************************************
PARAMETER INVESTMENT(CTRY,LC1,T);
INVESTMENT(CTRY,LC1,T)=

*planting costs accessible lands
(IMGMT1.L(CTRY,LC1,T))*(ACPL2.L(CTRY,LC1,T))$(R1FOR(CTRY,LC1) EQ 1)

*planting costs dedicated biofuels
+(IMGMT1.L(CTRY,LC1,T))*[ACPLBIO.L(CTRY,LC1,T)+NEWACPLBIO.L(CTRY,LC1,T)] $(DEDBIO(CTRY,LC1) EQ 1)

*planting costs dedicated biofuels
+ PARAM3(CTRY,LC1,'17')*(NEWACPLBIO.L(CTRY,LC1,T))$(DEDBIO(CTRY,LC1) EQ 1)

*planting costs TEMPERATE ZONE inaccessible
+(IMGMT1.L(CTRY,LC1,T))*(ACPL3.L(CTRY,LC1,T))$(TEMPINAC(CTRY,LC1) EQ 1)
 
*planting costs TROPICAL ZONE inaccessible original with ACPL6 only
+[IMGMT1.l(CTRY,LC1,T)+2000]*[ACPL6.l(CTRY,LC1,T)]$(TROPINAC(CTRY,LC1) EQ 1)
;

PARAMETER INVESTCTRY(CTRY,T);
INVESTCTRY(CTRY,T) =SUM(LC1,INVESTMENT(CTRY,LC1,T));


FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL INVESTMENT COST';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT INVESTCTRY(CTRY,T)););

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL RENTAL COST';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT RENTTOTALCTRY(CTRY,T)););

PARAMETER THARVCOST(CTRY,LC1,T);
THARVCOST(CTRY,LC1,T) = 

*sawtimber harvest cost

(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*
CSA(CTRY,LC1,'1')*SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))$(R1FOR(CTRY,LC1) EQ 1)

+

[
{(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON)*YIELD2(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))+EPSILON}** CSA(CTRY,LC1,'2')]$(R1FOR(CTRY,LC1) EQ 1)

*cost of sawtimber production on temperate semi-accessible lands
+
(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*
CSA(CTRY,LC1,'3')*SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON)*YIELD2(CTRY,LC1,A1,T)*
     PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))$(TEMPINAC(CTRY,LC1) EQ 1)

+
[{(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON)*YIELD2(CTRY,LC1,A1,T)*
     PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))+EPSILON}** CSA(CTRY,LC1,'4')]$(TEMPINAC(CTRY,LC1) EQ 1)

*cost of sawtimber production on tropical semi-accessible lands
+
(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*
CSA(CTRY,LC1,'3')*SUM(A1,[ACHR2.L(CTRY,LC1,A1,T) +EPSILON]*
        YIELD2(CTRY,LC1,A1,T)*
        PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))$(TROPINAC(CTRY,LC1) EQ 1)

+

[
{(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*SUM(A1,[ACHR2.L(CTRY,LC1,A1,T) +EPSILON]*
        YIELD2(CTRY,LC1,A1,T)*
        PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))+EPSILON}** CSA(CTRY,LC1,'4')]$(TROPINAC(CTRY,LC1) EQ 1)


*cost of harvesting temperate inaccessible lands
+
(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*
SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T) +EPSILON)*
PARAM2(CTRY,LC1,'12')*{CHQ1.L(CTRY,LC1,T)+EPSILON}**(1/PARAM2(CTRY,LC1,'13'))$(TEMPINAC(CTRY,LC1) EQ 1)


*cost of harvesting tropical inaccessible lands
+
(1-PROPPULP.L(CTRY,LC1,T) +EPSILON)*
{SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)+ ACHR3.L(CTRY,LC1,A1,T))+EPSILON}*
PARAM2(CTRY,LC1,'14')*
{SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)+ ACHR3.L(CTRY,LC1,A1,T))+EPSILON}**(1/PARAM2(CTRY,LC1,'15')) $(TROPINAC(CTRY,LC1) EQ 1)
*end of cost of sawtimber harvesting

+

*costs of pulpwood production

(PROPPULP.L(CTRY,LC1,T)+EPSILON)*
CSA(CTRY,LC1,'5')*SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON)*YIELD2(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))$(R1FOR(CTRY,LC1) EQ 1)

+
[
{(PROPPULP.L(CTRY,LC1,T)+EPSILON)*
SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*
PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))+EPSILON}** CSA(CTRY,LC1,'6')]$(R1FOR(CTRY,LC1) EQ 1)

*cost of harvesting temperate semi-accessible lands
+
(PROPPULP.L(CTRY,LC1,T)+EPSILON)*
CSA(CTRY,LC1,'7')*SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*
     PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))$(TEMPINAC(CTRY,LC1) EQ 1)

+
[
{(PROPPULP.L(CTRY,LC1,T) +EPSILON)*
SUM(A1,(ACHR2.L(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*
     PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))+EPSILON}** CSA(CTRY,LC1,'8')]$(TEMPINAC(CTRY,LC1) EQ 1)

*cost of harvesting tropical semi-accessible lands
+
(PROPPULP.L(CTRY,LC1,T)+EPSILON)*
CSA(CTRY,LC1,'7')*SUM(A1,[ACHR2.L(CTRY,LC1,A1,T) +EPSILON]*
        YIELD2(CTRY,LC1,A1,T)*
        PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))$(TROPINAC(CTRY,LC1) EQ 1)
+

[
{(PROPPULP.L(CTRY,LC1,T)+EPSILON)*SUM(A1,[ACHR2.L(CTRY,LC1,A1,T) +EPSILON]*
        YIELD2(CTRY,LC1,A1,T)*
        PARAM2(CTRY,LC1,'8')*((1+MGMT1.L(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T)))+EPSILON}** CSA(CTRY,LC1,'8')]$(TROPINAC(CTRY,LC1) EQ 1)


*cost of harvesting temperate inaccessible lands
+
(PROPPULP.L(CTRY,LC1,T)+EPSILON)*
SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T) +EPSILON)*
PARAM2(CTRY,LC1,'12')*{CHQ1.L(CTRY,LC1,T)+EPSILON}**(1/PARAM2(CTRY,LC1,'13'))$(TEMPINAC(CTRY,LC1) EQ 1)

*cost of harvesting tropical inaccessible lands
+
(PROPPULP.L(CTRY,LC1,T)+EPSILON)*
{SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)+ ACHR3.L(CTRY,LC1,A1,T))+EPSILON}*
PARAM2(CTRY,LC1,'14')*
{SUM(A1,ACHRIN1.L(CTRY,LC1,A1,T)+ ACHR3.L(CTRY,LC1,A1,T))+EPSILON}**(1/PARAM2(CTRY,LC1,'15'))$(TROPINAC(CTRY,LC1) EQ 1)
*end of cost of pulpwood harvesting

+

*dedicated biofuel harvesting costs
CSA(CTRY,LC1,'5')*[ SUM(A1,((ACHR2.l(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.l(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T))$(DEDBIO(CTRY,LC1) EQ 1)))]+
(SUM(A1,((ACHR2.l(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.l(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T))$(DEDBIO(CTRY,LC1) EQ 1)))+EPSILON)**CSA(CTRY,LC1,'6')

*transportation costs
+
[SUM(A1,((ACHR2.l(CTRY,LC1,A1,T) +EPSILON )*YIELD2(CTRY,LC1,A1,T)*PARAM2(CTRY,LC1,'8')*
       ((1+MGMT1.l(CTRY,LC1,A1,T))**FINPTEL(CTRY,LC1,T))$(DEDBIO(CTRY,LC1) EQ 1)))]*PARAM3(CTRY,LC1,'18')*PARAM3(CTRY,LC1,'19')
;

PARAMETER THARVCOSTCTRY(CTRY,T);
THARVCOSTCTRY(CTRY,T) = SUM(LC1,THARVCOST(CTRY,LC1,T));

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'REGIONAL HARVEST COST';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT THARVCOSTCTRY(CTRY,T)););

PARAMETER TOTALOUTPUT(CTRY,T);
TOTALOUTPUT(CTRY,T) = FPP(T)*QFP(CTRY,T) +FPS(T)*QFS(CTRY,T);

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'TOTAL OUTPUT';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT TOTALOUTPUT(CTRY,T)););

*total harvest

PARAMETER HECTAREHARV(CTRY,T);
HECTAREHARV(CTRY,T)=SUM(LC1,SUM(A1,
ACHR2.L(CTRY,LC1,A1,T)+ACHR3.L(CTRY,LC1,A1,T)+ACHRIN1.L(CTRY,LC1,A1,T)));

FILE  GTM_2020_R2; PUT  GTM_2020_R2;  GTM_2020_R2.PC=5;
PUT / 'HECTARES HARVESTED';
PUT / 'YEAR';
PUT 'US';
PUT 'CHINA';
PUT 'BRAZIL';
PUT 'CANADA';
PUT 'RUSSIA';
PUT 'EU ANNEX I';
PUT 'EU NON ANNEX I';
PUT 'SOUTH ASIA';
PUT 'CENT AMER.';
PUT 'RSAM';
PUT 'SSAF';
PUT 'SE ASIA';
PUT 'OCEANIA';
PUT 'JAPAN';
PUT 'AFME';
PUT 'E ASIA';
LOOP(T, PUT / T.TE(T);LOOP(CTRY, PUT HECTAREHARV(CTRY,T)););



* PLACES ALL OUTPUT TO A GDX FILE
execute_unload "GTM_2020_R2.gdx"

